<?php
	$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Export.css'), 'media' => 'all'));
	$this->headScript()->appendFile($this->baseUrl('javascript/export.js'));
?>

<h1>Create New Catalog Export Configuration</h1>

<form class='config-create-form' action="<?php print $this->url(array('action' => 'insertconfig')); ?>" method="post">
	<strong>Label:</strong><input name='label'></input>
	<strong>Catalog:</strong><br>
		<select name='catalog_id'>
			<option value='unselected'>Please choose a catalog</option>
			<?php
			while ($this->catalogs->hasNext()) {
				$catalog = $this->catalogs->getNextCourseCatalog();
				print "<option value='" . $this->getStringFromOsidId($catalog->getId()) . "'>" . $catalog->getDisplayName() . "</option>";
			}
			?>
		</select>
	<input class='submit-button' type='submit'></input>
</form>
