<?php
	$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Export.css'), 'media' => 'all'));
	$this->headScript()->appendFile($this->baseUrl('javascript/jsdifflib/difflib.js'));
	$this->headScript()->appendFile($this->baseUrl('javascript/revision_history.js'));
?>

<h1>Revision history for <?php echo $this->configLabel; ?></h1>
<div class='admin-menu'><a href="<?php print $this->url(array('controller' => 'admin', 'action' => 'export'), 'default'); ?>/<?php echo $this->configId; ?>">&laquo; Back to catalog export configuration</a></div>

<div class='config-menu'>
	<button onclick=compare('<?php print $this->url(array('controller' => 'export', 'action' => 'revisiondiff'), 'export_revisiondiff'); ?>')>Compare selected revisions</button>
</div>

<?php
	print $this->test;
	if ($this->revisions) {
		print "<table id='revisions-table'>";
		print "<th>Compare</th><th>Date</th><th>Author</th><th>Note</th><th>JSON</th><th>Actions</th>";
	  foreach($this->revisions as $revision) {
			print "<tr>";
			print "<td><input id='radio" . $revision['id'] . "' type=radio></input><input class='revId' type='hidden' value='" . $revision['id'] . "' /></td>";
			print "<td class='timestamp'>" . $revision['last_saved'] . "</td>";
			print "<td>" . $revision['user_disp_name'] . "</td>";
			print "<td width='200'>" . $revision['note'] . "</td>";
			print "<td><a class='link-button' href='" . $this->url(array('revision' => $revision['id']), 'export_viewjson') . "' target=_blank>View JSON</a></td>";
			print "<td><button onclick=revertTo(" . $revision['id'] . ")>Revert to this revision</button></td>";
			print "</tr>";
	  }
		print "</table>";
	}
	else {
		print "No revisions in history for config: " . $this->configLabel;
	}
?>
