<?php
	$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Export.css'), 'media' => 'all'));
	$this->headScript()->appendFile($this->baseUrl('javascript/jsdifflib/difflib.js'));
	$this->headScript()->appendFile($this->baseUrl('javascript/revision_history.js'));
?>

<h1>Revision history for <?php echo $this->configLabel; ?></h1>
<div class='admin-menu'><a href="<?php print $this->url(array('controller' => 'admin', 'action' => 'export')); ?>">&laquo; Back to catalog export configuration</a></div>

<div class='config-menu'>
	<button onclick=compare()>Compare selected revisions</button>
</div>

<form id="diff-form" class="hidden" action="revisiondiff" method="post" target="_blank">
	<input id="text1" type="hidden" name="text1" value="" />
	<input id="text2" type="hidden" name="text2" value="" />
	<input id="time1" type="hidden" name="time1" value="" />
	<input id="time2" type="hidden" name="time2" value="" />
</form>

<?php
	if ($this->revisions && $this->latestRevision) {
		print "<table id='revisions-table'>";
		print "<th>Compare</th><th>Date</th><th>Author</th><th>JSON</th><th>Actions</th>";
	  foreach($this->revisions as $revision) {
			print "<tr>";
			print "<td><input id='radio" . $revision['id'] . "' type=radio></input</td>";
			print "<td class='timestamp'>" . $revision['last_saved'] . "</td>";
			print "<td>" . $revision['user_disp_name'] . "</td>";
			print "<td width='300'><center><button onclick=showHide(" . $revision['id'] . ")>Show/Hide</button></center><div id='json" . $revision['id'] . "' class='json-data hidden'>" . $revision['json_data'] . "</div></td>";
			print "<td><button onclick=revertTo(" . $revision['id'] . ")>Revert to this revision</button></td>";
			print "</tr>";
	  }
		print "</table>";
	}
	else {
		print "No revisions in history for config: " . $this->configLabel;
	}
?>
