<?php

/**
 * Test class for banner_course_CourseOffering.
 * Generated by PHPUnit on 2009-04-16 at 10:31:07.
 */
class banner_course_CourseOfferingTest extends phpkit_test_phpunit_AbstractOsidObjectTest
{
    use banner_DatabaseTestTrait;

    /**
     * @var banner_course_CourseOffering
     */
    protected $object;

    /**
     * Answer the Object to test.
     *
     * @return osid_OsidObject
     *
     * @since 4/15/09
     */
    protected function getObject()
    {
        return $this->object;
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->mcugCatalogId = new phpkit_id_URNInetId('urn:inet:middlebury.edu:catalog.MCUG');
        $this->physCourseId = new phpkit_id_URNInetId('urn:inet:middlebury.edu:course.PHYS0201');
        $this->physOfferingId = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200890.90143');
        $this->geolOfferingId = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200890.92418');
        $this->geogOfferingId = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200890.92443');
        $this->chemOfferingId = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200520.20022');
        $this->session = self::$courseManager->getCourseOfferingLookupSessionForCatalog($this->mcugCatalogId);
        $this->object = $this->session->getCourseOffering($this->physOfferingId);

        $this->instructorsType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:instructors');
        $this->weeklyScheduleType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:weekly_schedule');
        $this->alternatesType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:alternates');

        $this->namesType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:person_names');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public function testOfferingGetDisplayName()
    {
        $this->assertEquals('PHYS0201A-F08', $this->object->getDisplayName());
    }

    public function testGenusType()
    {
        $type = $this->object->getGenusType();
        $this->assertInstanceOf('osid_type_Type', $type);
        $this->assertEquals('genera:offering.LCT', $type->getIdentifier());
        $this->assertEquals('Lecture', trim($type->getDisplayName()));
    }

    public function testGetTitle()
    {
        $this->assertIsString($this->object->getTitle());
        $this->assertEquals('Relativity And Quantum Physics', $this->object->getTitle());
    }

    /**
     * Test that the title of the chemistry Course has the more recent version of the title.
     * Effective 200390 and 200490, the title is "Fundamentals of Chemistry II", however
     * effective 200520, the title changed to "General Chemistry II".
     */
    public function testEffectiveDateTitle()
    {
        $chem200390 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200390.90085');
        $chem200420 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200420.20073');
        $chem200490 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200490.90066');
        $chem200520 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200520.20019');
        $chem200590 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200590.90056');
        $chem200620 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200620.20017');
        $chem200890 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200890.90040');

        $this->assertEquals('Fundamentals of Chemistry II', $this->session->getCourseOffering($chem200390)->getTitle());
        $this->assertEquals('Fundamentals of Chemistry II', $this->session->getCourseOffering($chem200420)->getTitle());
        $this->assertEquals('Fundamentals of Chemistry II', $this->session->getCourseOffering($chem200490)->getTitle());
        $this->assertEquals('General Chemistry II', $this->session->getCourseOffering($chem200520)->getTitle());
        $this->assertEquals('General Chemistry II', $this->session->getCourseOffering($chem200590)->getTitle());
        $this->assertEquals('General Chemistry II', $this->session->getCourseOffering($chem200620)->getTitle());
        $this->assertEquals('General Chemistry II', $this->session->getCourseOffering($chem200890)->getTitle());
    }

    public function testGetPhysDescription()
    {
        $this->assertEquals("This course probes a number of areas for which classical physics has provided no adequate explanations. Topics covered include Einstein's special relativity, quantization of atomic energy levels and photons, the atomic models of Rutherford and Bohr, and wave-particle duality. (PHYS 0109, MATH 0122, PHYS 0110 concurrent or prior) 3 hrs. lect.", $this->object->getDescription());
    }

    /**
     * Test that the title of the chemistry Course has the more recent version of the description.
     * Effective 200490, the a decription exists. Prior to that there is no description.
     */
    public function testEffectiveDateDescription()
    {
        $chem200390 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200390.90085');
        $chem200420 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200420.20073');
        $chem200490 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200490.90066');
        $chem200520 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200520.20019');
        $chem200590 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200590.90056');
        $chem200620 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200620.20017');
        $chem200890 = new phpkit_id_URNInetId('urn:inet:middlebury.edu:section.200890.90040');

        $description = 'Major topics include chemical kinetics, chemical equilibrium, acid-base equilibria, chemical thermodynamics, electrochemistry, descriptive inorganic chemistry, and coordination chemistry. Lab work includes inorganic synthesis, qualitative analysis, and quantitative analysis in kinetics, acid-base and redox chemistry. (CHEM 0103 or by waiver) 3 hrs. lect., 3 hrs. lab, 1 hr. disc.';

        $this->assertEquals('', $this->session->getCourseOffering($chem200390)->getDescription());
        $this->assertEquals('', $this->session->getCourseOffering($chem200420)->getDescription());
        $this->assertEquals($description, $this->session->getCourseOffering($chem200490)->getDescription());
        $this->assertEquals($description, $this->session->getCourseOffering($chem200520)->getDescription());
        $this->assertEquals($description, $this->session->getCourseOffering($chem200590)->getDescription());
        $this->assertEquals($description, $this->session->getCourseOffering($chem200620)->getDescription());
        $this->assertEquals($description, $this->session->getCourseOffering($chem200890)->getDescription());
    }

    public function testChemGetNumber()
    {
        $object = $this->session->getCourseOffering($this->chemOfferingId);
        $this->assertIsString($object->getNumber());
        $this->assertEquals('CHEM0104T-S05', $object->getNumber());
    }

    public function testGetNumber()
    {
        $this->assertIsString($this->object->getNumber());
        $this->assertEquals('PHYS0201A-F08', $this->object->getNumber());
    }

    public function testGetCredits()
    {
        $this->assertIsFloat($this->object->getCredits());
        $this->assertEquals(1.00, $this->object->getCredits());
    }

    public function testGetPrereqInfo()
    {
        $this->assertIsString($this->object->getPrereqInfo());
    }

    public function testGetCourseId()
    {
        $this->assertInstanceOf('osid_id_Id', $this->object->getCourseId());
    }

    public function testGetCourse()
    {
        $this->assertInstanceOf('osid_course_Course', $this->object->getCourse());
    }

    public function testGetTermId()
    {
        $this->assertInstanceOf('osid_id_Id', $this->object->getTermId());
    }

    public function testGetTerm()
    {
        $this->assertInstanceOf('osid_course_Term', $this->object->getTerm());
    }

    public function testGetTopicIds()
    {
        $list = $this->object->getTopicIds();
        $this->assertInstanceOf('osid_id_IdList', $list);
        $this->assertEquals(6, $list->available());
        $this->assertInstanceOf('osid_id_Id', $list->getNextId());
    }

    public function testGetTopics()
    {
        $list = $this->object->getTopics();
        $this->assertInstanceOf('osid_course_TopicList', $list);
        $this->assertEquals(6, $list->available());
        $this->assertInstanceOf('osid_course_Topic', $list->getNextTopic());
    }

    public function testTopicIds()
    {
        $list = $this->object->getTopicIds();
        $identifiers = [
            'topic.subject.PHYS',
            'topic.department.PHYS',
            'topic.division.NSCI',
            'topic.requirement.DED',
            'topic.requirement.SCI',
            'topic.level.UG',
        ];
        $found = [];
        $this->assertTrue($list->hasNext());
        while ($list->hasNext()) {
            $found[] = $list->getNextId()->getIdentifier();
        }
        foreach ($identifiers as $id) {
            if (!in_array($id, $found)) {
                $this->fail('Topic "'.$id.'" was not found.');
            }
        }
    }

    public function testGeolGetTopics()
    {
        $offering = $this->session->getCourseOffering($this->geolOfferingId);
        $list = $offering->getTopics();
        $this->assertInstanceOf('osid_course_TopicList', $list);
        $this->assertEquals(7, $list->available());
        $this->assertInstanceOf('osid_course_Topic', $list->getNextTopic());
    }

    public function testGeolTopicIds()
    {
        $offering = $this->session->getCourseOffering($this->geolOfferingId);
        $list = $offering->getTopicIds();
        $this->assertEquals(7, $list->available());
        $identifiers = [
            'topic.subject.GEOL',
            'topic.department.GEOL',
            'topic.division.NSCI',
            'topic.requirement.DED',
            'topic.requirement.SCI',
            'topic.level.UG',
            'topic.block.CC',
        ];
        $found = [];
        while ($list->hasNext()) {
            $found[] = $list->getNextId()->getIdentifier();
        }
        foreach ($identifiers as $id) {
            if (!in_array($id, $found)) {
                $this->fail('Topic "'.$id.'" was not found.');
            }
        }
    }

    public function testGetLocationInfo()
    {
        $this->assertIsString($this->object->getLocationInfo());
        //         $this->assertEquals('', $this->object->getLocationInfo());
    }

    public function testHasLocation()
    {
        $this->assertIsBool($this->object->hasLocation());
    }

    public function testGetLocationId()
    {
        if ($this->object->hasLocation()) {
            $this->assertInstanceOf('osid_id_Id', $this->object->getLocationId());
        } else {
            try {
                $this->object->getLocationId();
                $this->fail('Should have thrown an osid_IllegalStateException');
            } catch (osid_IllegalStateException $e) {
                $this->assertTrue(true);
            }
        }
    }

    public function testGetLocation()
    {
        if ($this->object->hasLocation()) {
            try {
                $this->assertInstanceOf('osid_resource_Resource', $this->object->getLocation());
            } catch (osid_OperationFailedException $e) {
                $this->markTestIncomplete($e->getMessage().' - getResourceManager() needs to be fully implemented..');
            }
        } else {
            try {
                $this->object->getLocation();
                $this->fail('Should have thrown an osid_IllegalStateException');
            } catch (osid_IllegalStateException $e) {
                $this->assertTrue(true);
            }
        }
    }

    public function testGetScheduleInfo()
    {
        $this->assertIsString($this->object->getScheduleInfo());
        //         $this->assertEquals('', $this->object->getScheduleInfo());
    }

    public function testHasCalendar()
    {
        $this->assertIsBool($this->object->hasCalendar());
    }

    public function testGetCalendarId()
    {
        if ($this->object->hasCalendar()) {
            $this->assertInstanceOf('osid_id_Id', $this->object->getCalendarId());
        } else {
            try {
                $this->object->getCalendarId();
                $this->fail('Should have thrown an osid_IllegalStateException');
            } catch (osid_IllegalStateException $e) {
                $this->assertTrue(true);
            }
        }
    }

    public function testGetCalendar()
    {
        if ($this->object->hasCalendar()) {
            $this->assertInstanceOf('osid_resource_Resource', $this->object->getCalendar());
        } else {
            try {
                $this->object->getCalendar();
                $this->fail('Should have thrown an osid_IllegalStateException');
            } catch (osid_IllegalStateException $e) {
                $this->assertTrue(true);
            }
        }
    }

    public function testHasLearningObjective()
    {
        $this->assertIsBool($this->object->hasLearningObjective());
    }

    public function testGetLearningObjectiveId()
    {
        if ($this->object->hasLearningObjective()) {
            $this->assertInstanceOf('osid_id_Id', $this->object->getLearningObjectiveId());
        } else {
            try {
                $this->object->getLearningObjectiveId();
                $this->fail('Should have thrown an osid_IllegalStateException');
            } catch (osid_IllegalStateException $e) {
                $this->assertTrue(true);
            }
        }
    }

    public function testGetLearningObjective()
    {
        if ($this->object->hasLearningObjective()) {
            $this->assertInstanceOf('osid_id_Id', $this->object->getLearningObjective());
        } else {
            try {
                $this->object->getLearningObjective();
                $this->fail('Should have thrown an osid_IllegalStateException');
            } catch (osid_IllegalStateException $e) {
                $this->assertTrue(true);
            }
        }
    }

    /**
     * @todo Implement testGetURL().
     */
    public function testGetURL()
    {
        $this->assertIsString($this->object->getURL());
    }

    public function testGetCourseOfferingRecord()
    {
        $types = $this->object->getRecordTypes();
        while ($types->hasNext()) {
            $this->assertInstanceOf('osid_course_CourseOfferingRecord', $this->object->getCourseOfferingRecord($types->getNextType()));
        }
    }

    public function testHasInstructorsRecord()
    {
        $this->assertTrue($this->object->hasRecordType($this->instructorsType));
    }

    public function testGetInstructorsRecord()
    {
        $record = $this->object->getCourseOfferingRecord($this->instructorsType);
        $this->assertInstanceOf('osid_course_CourseOfferingRecord', $record);
        $this->assertInstanceOf('middlebury_course_CourseOffering_InstructorsRecord', $record);
    }

    public function testInstructorsRecordGetInstructorIds()
    {
        $record = $this->object->getCourseOfferingRecord($this->instructorsType);
        $ids = $record->getInstructorIds();
        $this->assertInstanceOf('osid_id_IdList', $ids);
        $this->assertEquals(1, $ids->available());
        $this->assertInstanceOf('osid_id_Id', $ids->getNextId());
    }

    public function testInstructorsRecordGetInstructors()
    {
        $record = $this->object->getCourseOfferingRecord($this->instructorsType);
        $instructors = $record->getInstructors();
        $this->assertInstanceOf('osid_resource_ResourceList', $instructors);
        $this->assertEquals(1, $instructors->available());
        $person = $instructors->getNextResource();
        $this->assertInstanceOf('osid_resource_Resource', $person);
        $this->assertEquals('Nevin Nordemire', $person->getDisplayName());

        $names = $person->getResourceRecord($this->namesType);
        $this->assertEquals('Nevin', $names->getGivenName());
        $this->assertEquals('Nordemire', $names->getSurname());
    }

    public function testChemInstructorsRecordGetInstructorIds()
    {
        $object = $this->session->getCourseOffering($this->chemOfferingId);
        $record = $object->getCourseOfferingRecord($this->instructorsType);
        $ids = $record->getInstructorIds();
        $this->assertInstanceOf('osid_id_IdList', $ids);
        $this->assertEquals(2, $ids->available());
        $this->assertInstanceOf('osid_id_Id', $ids->getNextId());
    }

    public function testChemInstructorsRecordGetInstructors()
    {
        $object = $this->session->getCourseOffering($this->chemOfferingId);
        $record = $object->getCourseOfferingRecord($this->instructorsType);
        $instructors = $record->getInstructors();
        $this->assertInstanceOf('osid_resource_ResourceList', $instructors);
        $this->assertEquals(2, $instructors->available());

        $person = $instructors->getNextResource();
        $this->assertInstanceOf('osid_resource_Resource', $person);
        $this->assertEquals('Barry Bancroft', $person->getDisplayName());

        $names = $person->getResourceRecord($this->namesType);
        $this->assertEquals('Barry', $names->getGivenName());
        $this->assertEquals('Bancroft', $names->getSurname());

        $person = $instructors->getNextResource();
        $this->assertInstanceOf('osid_resource_Resource', $person);
        $this->assertEquals('Georges Gleuseau', $person->getDisplayName());

        $names = $person->getResourceRecord($this->namesType);
        $this->assertEquals('Georges', $names->getGivenName());
        $this->assertEquals('Gleuseau', $names->getSurname());
    }

    /*********************************************************
     * Tests for AlternatesRecord.
     *********************************************************/
    public function testHasAlternates()
    {
        $record = $this->object->getCourseOfferingRecord($this->alternatesType);
        $this->assertFalse($record->hasAlternates());
    }

    public function testGetAlternateIds()
    {
        $record = $this->object->getCourseOfferingRecord($this->alternatesType);
        $ids = $record->getAlternateIds();
        $this->assertInstanceOf('osid_id_IdList', $ids);
    }

    public function testGetAlternates()
    {
        $record = $this->object->getCourseOfferingRecord($this->alternatesType);
        $alternates = $record->getAlternates();
        $this->assertInstanceOf('osid_course_CourseOfferingList', $alternates);
    }

    public function testHasGeolAlternates()
    {
        $offering = $this->session->getCourseOffering($this->geolOfferingId);
        $record = $offering->getCourseOfferingRecord($this->alternatesType);
        $this->assertTrue($record->hasAlternates());
    }

    public function testGetGeolAlternateIds()
    {
        $offering = $this->session->getCourseOffering($this->geolOfferingId);
        $record = $offering->getCourseOfferingRecord($this->alternatesType);
        $ids = $record->getAlternateIds();
        $this->assertInstanceOf('osid_id_IdList', $ids);
        $this->assertEquals(1, $ids->available());
    }

    public function testGetGeolAlternates()
    {
        $offering = $this->session->getCourseOffering($this->geolOfferingId);
        $record = $offering->getCourseOfferingRecord($this->alternatesType);
        $alternates = $record->getAlternates();
        $this->assertInstanceOf('osid_course_CourseOfferingList', $alternates);
        $this->assertEquals(1, $alternates->available());
    }

    public function testGeogIsPrimary()
    {
        $offering = $this->session->getCourseOffering($this->geogOfferingId);
        $record = $offering->getCourseOfferingRecord($this->alternatesType);
        $this->assertFalse($record->isPrimary());
    }

    public function testGeolIsPrimary()
    {
        $offering = $this->session->getCourseOffering($this->geolOfferingId);
        $record = $offering->getCourseOfferingRecord($this->alternatesType);
        $this->assertTrue($record->isPrimary());
    }

    /*********************************************************
     * Tests for weeklySchedule record.
     *********************************************************/

    public function testMeetsOnSunday()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $this->assertFalse($record->meetsOnSunday());
    }

    public function testGetSundayStartTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getSundayStartTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }

    public function testGetSundayEndTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getSundayEndTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }

    public function testMeetsOnMonday()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $this->assertTrue($record->meetsOnMonday());
    }

    public function testGetMondayStartTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getMondayStartTimes();
        $this->assertIsArray($times);
        $this->assertCount(1, $times);
        $this->assertEquals(40500, $times[0]);	// 11:15am
    }

    public function testGetMondayEndTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getMondayEndTimes();
        $this->assertIsArray($times);
        $this->assertCount(1, $times);
        $this->assertEquals(43500, $times[0]);	// 12:05pm
    }

    public function testMeetsOnTuesday()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $this->assertFalse($record->meetsOnTuesday());
    }

    public function testGetTuesdayStartTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getTuesdayStartTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }

    public function testGetTuesdayEndTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getTuesdayEndTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }

    public function testMeetsOnWednesday()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $this->assertTrue($record->meetsOnWednesday());
    }

    public function testGetWednesdayStartTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getWednesdayStartTimes();
        $this->assertIsArray($times);
        $this->assertCount(1, $times);
        $this->assertEquals(40500, $times[0]);	// 11:15am
    }

    public function testGetWednesdayEndTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getWednesdayEndTimes();
        $this->assertIsArray($times);
        $this->assertCount(1, $times);
        $this->assertEquals(43500, $times[0]);	// 12:05pm
    }

    public function testMeetsOnThursday()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $this->assertFalse($record->meetsOnThursday());
    }

    public function testGetThursdayStartTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getThursdayStartTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }

    public function testGetThursdayEndTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getThursdayEndTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }

    public function testMeetsOnFriday()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $this->assertTrue($record->meetsOnFriday());
    }

    public function testGetFridayStartTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getFridayStartTimes();
        $this->assertIsArray($times);
        $this->assertCount(1, $times);
        $this->assertEquals(40500, $times[0]);	// 11:15am
    }

    public function testGetFridayEndTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getFridayEndTimes();
        $this->assertIsArray($times);
        $this->assertCount(1, $times);
        $this->assertEquals(43500, $times[0]);	// 12:05pm
    }

    public function testMeetsOnSaturday()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $this->assertFalse($record->meetsOnSaturday());
    }

    public function testGetSaturdayStartTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getSaturdayStartTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }

    public function testGetSaturdayEndTimes()
    {
        $record = $this->object->getCourseOfferingRecord($this->weeklyScheduleType);
        $times = $record->getSaturdayEndTimes();
        $this->assertIsArray($times);
        $this->assertCount(0, $times);
    }
}
