<?php

use PHPUnit\Framework\TestCase;

/**
 * Test class for Catalog_Action_Helper_OsidId.
 * Generated by PHPUnit on 2009-06-11 at 09:36:05.
 */
class Catalog_Action_Helper_OsidIdTest extends TestCase
{
    use Catalog_ApplicationTestTrait;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->osidHelper = new Catalog_Action_Helper_Osid();
        Zend_Controller_Action_HelperBroker::addHelper($this->osidHelper);
        $this->osidIdHelper = new Catalog_Action_Helper_OsidId();
        Zend_Controller_Action_HelperBroker::addHelper($this->osidIdHelper);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    public function testGetOsidIdFromString()
    {
        $id = new phpkit_id_Id('example.edu', 'urn', '123456789.abcd');
        $idString = $this->osidIdHelper->toString($id);

        $newId = $this->osidIdHelper->fromString($idString);
        $this->assertInstanceOf('osid_id_Id', $newId);
        $this->assertTrue($id->isEqual($newId));
    }

    public function testGetStringFromOsidId()
    {
        $id = new phpkit_id_Id('example.edu', 'urn', '123456789.abcd');
        $idString = $this->osidIdHelper->toString($id);
        $this->assertIsString($idString);

        $newId = $this->osidIdHelper->fromString($idString);
        $this->assertEquals($idString, $this->osidIdHelper->toString($newId));
    }
}
