<?php

$this->headScript()->appendFile(
	$this->url(array(), null, true).'javascript/jquery.expander.js',
	'text/javascript'
);
$this->headScript()->appendScript(
	"
	$('document').ready(function() {
		$('div.description').expander({
			slicePoint:       140,  // default is 100
			expandPrefix:     '... ', // text to come before the expand link
			expandText:         'read more', // default is 'read more...'
			userCollapseText: '[collapse]'  // default is '[collapse expanded text]'
		});
	});
	",
	'text/javascript'
);

	$formParams = array(
							'controller'	=> 'offerings',
							'action'		=> 'search',
							'term'			=> null,
							'department'	=> null,
							'subject'		=> null,
							'division'		=> null,
							'requirement'	=> null,
							'level'	=> null,
							'days'			=> null,
							'time_start'	=> null,
							'time_end'		=> null,
							'keywords'		=> null,
							'page'			=> null,
							'submit'		=> null
						);
?>

<form action="<?php print $this->url($formParams); ?>" method="get">
	<table class='search_options'>
		<tr>
			<td colspan='2'><input type='submit' name='search' value='Search'/></td>
		</tr>
		<tr>
			<th>By Term:</th>
			<td>
				<select name="term" onchange="this.form['search'].value = ''; this.form.submit();">
					<option value='ANY'>Any Term</option>
<?php
while ($this->terms->hasNext()) {
	$term = $this->terms->getNextTerm();
	print "\n\t\t\t\t\t<option value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($term->getId()));
	print "'";
	if (isset($this->selectedTermId) && $term->getId()->isEqual($this->selectedTermId))
		print " selected='selected'";
	print ">".$this->escape($term->getDisplayName())."</option>";
}
?>
				</select>
			</td>
		</tr>

		<tr>
			<th>By Subject/Department:</th>
			<td>
				<select name="department">
					<option value=''>Any Subject or Department</option>
					<optgroup label='Subjects'>
<?php
while ($this->subjects->hasNext()) {
	$topic = $this->subjects->getNextTopic();
	print "\n\t\t\t\t\t<option value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($topic->getId()));
	print "'";
	if (isset($this->selectedDepartmentId) && $topic->getId()->isEqual($this->selectedDepartmentId))
		print " selected='selected'";
	print ">".$this->escape($topic->getDisplayName())."</option>";
}
?>
					</optgroup>
					<optgroup label='Departments'>
<?php
while ($this->departments->hasNext()) {
	$topic = $this->departments->getNextTopic();
	print "\n\t\t\t\t\t<option value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($topic->getId()));
	print "'";
	if (isset($this->selectedDepartmentId) && $topic->getId()->isEqual($this->selectedDepartmentId))
		print " selected='selected'";
	print ">".$this->escape($topic->getDisplayName())."</option>";
}
?>
					</optgroup>
				</select>
			</td>
		</tr>

<?php	if ($this->requirements->hasNext()) { ?>
		<tr>
			<th>Satisfies Requirements:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='requirement_group'>
<?php
$i = 0;
while ($this->requirements->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";

	$topic = $this->requirements->getNextTopic();
	print "\n\t\t\t\t<input type='checkbox' name='requirement[]' value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($topic->getId()));
	print "'";
	foreach ($this->selectedRequirementIds as $selectedId) {
		if ($topic->getId()->isEqual($selectedId)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$this->escape($topic->getDisplayName())."</label><br/>";

	$i++;
}
?>
				</div>
			</td>
		</tr>
<?php	} ?>
		<tr>
			<th>Keywords:</th>
			<td>
				<input class='text_input' type='text' name='keywords' value='<?php print $this->escapeHtmlAttr($this->keywords); ?>' />
				<div class='help_text'>By default results only have to match one of the supplied keywords. Use a plus (+) before a word to require it or a minus (-) to exclude it. Use an asterisk (*) as a wildcard.</div>
			</td>
		</tr>

<?php if (isset($this->searchParams['days'])) { ?>
		<tr>
			<th>Days of the week:</th>
			<td>
				<label><input type='checkbox' name='days[]' value='sunday' <?php if (in_array('sunday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Sunday</label>
				<label><input type='checkbox' name='days[]' value='monday' <?php if (in_array('monday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Monday</label>
				<label><input type='checkbox' name='days[]' value='tuesday' <?php if (in_array('tuesday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Tuesday</label>
				<label><input type='checkbox' name='days[]' value='wednesday' <?php if (in_array('wednesday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Wednesday</label>
				<label><input type='checkbox' name='days[]' value='thursday' <?php if (in_array('thursday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Thursday</label>
				<label><input type='checkbox' name='days[]' value='friday' <?php if (in_array('friday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Friday</label>
				<label><input type='checkbox' name='days[]' value='saturday' <?php if (in_array('saturday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Saturday</label>
				<div class='help_text'>Leave all unchecked if no preference.</div>
			</td>
		</tr>

		<tr>
			<th>Time:</th>
			<td>
				<label>From
				<select name='time_start' class='time_select'>
					<option value='0'<?php if (!$this->timeStart) { print  " selected='selected'"; } ?>>Any Time</option>
<?php
	for ($i = 1800; $i < 86400; $i = $i + 1800) {
		print "\n\t\t\t\t\t<option value='$i'";
		if ($this->timeStart == $i)
			print " selected='selected'";
		print ">".$this->getTimeString($i)."</option>";
	}
?>
				</select>
				</label>

				<label>To
				<select name='time_end' class='time_select'>
<?php
	for ($i = 1800; $i < 86400; $i = $i + 1800) {
		print "\n\t\t\t\t\t<option value='$i'";
		if ($this->timeEnd == $i)
			print " selected='selected'";
		print ">".$this->getTimeString($i)."</option>";
	}
?>
				<option value='86400'<?php if ($this->timeEnd == 86400) { print  " selected='selected'"; } ?>>Any Time</option>
				</select>
				</label>
			</td>
		</tr>

		<tr>
			<th>Type:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='requirement_group'>
<?php
$i = 0;
while ($this->genusTypes->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";

	$type = $this->genusTypes->getNextType();
	print "\n\t\t\t\t<input type='checkbox' name='type[]' value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidType($type));
	print "'";
	foreach ($this->selectedGenusTypes as $selectedType) {
		if ($type->isEqual($selectedType)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$this->escape($type->getDisplayName())."</label><br/>";

	$i++;
}
?>
				</div>
			</td>
		</tr>

<?php	if ($this->blocks->hasNext()) { ?>
		<tr>
			<th>Additional Details:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='block_group'>
<?php
$i = 0;
while ($this->blocks->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";

	$topic = $this->blocks->getNextTopic();
	print "\n\t\t\t\t<input type='checkbox' name='block[]' value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($topic->getId()));
	print "'";
	foreach ($this->selectedBlockIds as $selectedId) {
		if ($topic->getId()->isEqual($selectedId)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$this->escape($topic->getDisplayName())."</label><br/>";

	$i++;
}
?>
				</div>
			</td>
		</tr>
<?php	} ?>

<?php	if ($this->instructionMethods->hasNext()) { ?>
		<tr>
			<th>Course Modality:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='instruction_method_group'>
<?php
$i = 0;
while ($this->instructionMethods->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";

	$topic = $this->instructionMethods->getNextTopic();
	print "\n\t\t\t\t<input type='checkbox' name='instruction_method[]' value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($topic->getId()));
	print "'";
	foreach ($this->selectedInstructionMethodIds as $selectedId) {
		if ($topic->getId()->isEqual($selectedId)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$this->escape($topic->getDisplayName())."</label><br/>";

	$i++;
}
?>
				</div>
			</td>
		</tr>
<?php	} ?>

		<tr>
			<th>Level:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='requirement_group'>
<?php
$i = 0;
while ($this->levels->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";

	$topic = $this->levels->getNextTopic();
	print "\n\t\t\t\t<input type='checkbox' name='level[]' value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($topic->getId()));
	print "'";
	foreach ($this->selectedLevelIds as $selectedId) {
		if ($topic->getId()->isEqual($selectedId)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$this->escape($topic->getDisplayName())."</label><br/>";

	$i++;
}
?>
				</div>
			</td>
		</tr>

<?php
if (isset($this->campuses) && $this->campuses->hasNext()) {
?>
		<tr>
			<th>Campus:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='requirement_group'>
<?php
$i = 0;
while ($this->campuses->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";

	$campus = $this->campuses->getNextResource();
	print "\n\t\t\t\t<input type='checkbox' name='location[]' value='";
	print $this->escapeHtmlAttr($this->getStringFromOsidId($campus->getId()));
	print "'";

	foreach ($this->selectedCampusIds as $selectedId) {
		if ($campus->getId()->isEqual($selectedId)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$this->escape($campus->getDisplayName())."</label><br/>";

	$i++;
}
?>
				</div>
			</td>
		</tr>
<?php } ?>

<?php } ?>

		<tr>
			<td colspan='2'><input type='submit' name='search' value='Search'/></td>
		</tr>

	</table>
</form>

<?php
/*********************************************************
 * Search results
 *********************************************************/
if (isset($this->paginator)) {

?>
<h2>Results</h2>

<?php
if (!count($this->paginator)) {
	print "<div class='search_empty'>No Matches</div>";
}

print $this->paginationControl($this->paginator, 'Sliding', 'ItemPaginationControl.phtml', array('search_params' => $this->searchParams)); ?>

<table class='search_results'>
	<tbody>
<?php
	$alternateType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:alternates');

	foreach ($this->paginator as $section) {
		$offeringParams = array(
							'controller'	=> 'offerings',
							'action'		=> 'view',
							'offering'		=> $this->getStringFromOsidId($section->getId())
						);
		$resourceParams = array(
							'controller'	=> 'resources',
							'action'		=> 'view',
							'term'			=> $this->getStringFromOsidId($term->getId()),
							'offering'		=> null
						);

		$term = $section->getTerm();
		$termUrl = $this->url(array(
						'controller'	=> 'terms',
						'action'		=> 'view',
						'term'			=> $this->getStringFromOsidId($term->getId()),
						'offering'		=> null
					));
		$topicParams = array(
						'controller'	=> 'topics',
						'action'		=> 'view',
						'offering'		=> null,
						'term'			=> $this->getStringFromOsidId($term->getId())
					);

		// Topics
		$allTopics = $this->topicListAsArray($section->getTopics());
?>
		<tr>
			<td class='column1'>
				<a class='title' href='<?php print $this->url($offeringParams); ?>'><?php print $this->escape($section->getDisplayName()); ?></a>
<?php

if ($section->hasRecordType($alternateType)) {
	$record = $section->getCourseOfferingRecord($alternateType);
	if ($record->hasAlternates()) {
		if ($record->isPrimary()) {
			print " * ";
		}

		$alternates = $record->getAlternates();
		print "\n\t\t\t\t<br/>Cross-Listed As:";
		while ($alternates->hasNext()) {
			print "\n\t\t\t\t<br/>";
			$alternate = $alternates->getNextCourseOffering();
			$offeringParams['offering'] = $this->getStringFromOsidId($alternate->getId());
			print "<a class='title' href=\"".$this->url($offeringParams)."\">";
			print $this->escape($alternate->getDisplayName());
			print "</a> ";
			if ($alternate->hasRecordType($alternateType)) {
				$alternateRecord = $alternate->getCourseOfferingRecord($alternateType);
				if ($alternateRecord->isPrimary()) {
					print " * ";
				}
			}
		}
	}
}

print "\n\t<dl>";

print "\n\t\t<dt>Type:</dt>";
print "\n\t\t<dd>".$this->escape($section->getGenusType()->getDisplayName())."</dd>";

$topics = $this->filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/instruction_method"));
if (!empty($topics)) {
	print "\n\t\t<dt>Course Modality:</dt>";
	print "\n\t\t<dd>";
	foreach ($topics as $topic) {
		$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
		print "<a href=\"".$this->url($topicParams)."\">";
		print $this->escape($topic->getDisplayName());
		print "</a> ";
	}
	print "</dd>";
}

print "\n\t\t<dt>Term:</dt>";
+print "\n\t\t<dd>";
+// print "\n\t\t\t<a href='".$termUrl."'>";
+print $this->escape($term->getDisplayName());
+// print "</a>";
+print "\n\t\t</dd>";
print "\n\t\t<dt>Department:</dt>";
print "\n\t\t<dd>";
$topics = $this->filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/department"));
foreach ($topics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Requirements Fulfilled:</dt>";
print "\n\t\t<dd>";
$topics = $this->filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/requirement"));
foreach ($topics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t</dl>";

$topics = $this->filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/block"));
if (!empty($topics)) {
	print "\n\t\t<dt>Additional Details:</dt>";
	print "\n\t\t<dd>";
	foreach ($topics as $topic) {
		$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
		print "<a href=\"".$this->url($topicParams)."\">";
		print $this->escape($topic->getDisplayName());
		print "</a> ";
	}
	print "</dd>";
}

?>


			</td>
			<td class='column2'>
				<?php
				$this->bookmarks_CourseId = $section->getCourseId();
				$this->bookmarks_IsCourseSaved = false;
				print $this->render('schedules/bookmark_control.phtml');
				?>
				<div class='title'><?php print nl2br($this->escape($section->getTitle())); ?></div>
				<div class='description'><?php print $section->getDescription(); ?></div>
<?php
print "\n\t<dl>";

$instructorsType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:instructors');
if ($section->hasRecordType($instructorsType)) {
	$instructorsRecord = $section->getCourseOfferingRecord($instructorsType);
	print "\n\t\t<dt>Instructors:</dt>";
	print "\n\t\t<dd>";
	$instructors = $instructorsRecord->getInstructors();
	while ($instructors->hasNext()) {
		$instructor = $instructors->getNextResource();
		$resourceParams['resource'] = $this->getStringFromOsidId($instructor->getId());
		print "<a href=\"".$this->url($resourceParams)."\">";
		print $this->escape($instructor->getDisplayName());
		print "</a> ";
	}
	print "</dd>";
}

if ($section->hasLocation()) {
	print "\n\t\t<dt>Location:</dt>";
	try {
		$locationResource = $section->getLocation();
		print "\n\t\t<dd>";
// 		$resourceParams['resource'] = $this->getStringFromOsidId($locationResource->getId());
// 		print "<a href=\"".$this->url($resourceParams)."\">";
		print $this->escape($locationResource->getDisplayName());
// 		print "</a> ";
		if ($locationResource->getDescription())
			print " <span class='location_description'>(".$this->escape($locationResource->getDescription()).")</span>";
		print "\n\t\t</dd>";
	} catch (osid_OperationFailedException $e) {
		print "\n\t\t<dd>".$this->escape($section->getLocationInfo())."</dd>";
	}
} else if ($section->getLocationInfo()) {
	print "\n\t\t<dt>Location:</dt>";
	print "\n\t\t<dd>".$this->escape($section->getLocationInfo())."</dd>";
}

print "\n\t\t<dt>Schedule:</dt>";
print "\n\t\t<dd>".$this->formatScheduleInfo($section->getScheduleInfo())."</dd>";

$availabilityLink = $this->getAvailabilityLink($section);
if (!empty($availabilityLink)) {
	print "\n\t\t<dt>Availability:</dt>";
	print "\n\t\t<dd>";
	print $availabilityLink;
	print "\n\t\t</dd>";
}

// print "\n\t<dt>Subject:</dt>";
// print "\n\t\t<dd>";
// $topics = $this->filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/subject"));
// foreach ($topics as $topic) {
// 	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
// 	print "<a href=\"".$this->url($topicParams)."\">";
// 	print $this->escape($topic->getDisplayName());
// 	print "</a> ";
// }
// print "</dd>";

// print "\n\t\t<dt>Division:</dt>";
// print "\n\t\t<dd>";
// $topics = $this->filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/division"));
// foreach ($topics as $topic) {
// 	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
// 	print "<a href=\"".$this->url($topicParams)."\">";
// 	print $this->escape($topic->getDisplayName());
// 	print "</a> ";
// }
// print "</dd>";

print "\n\t</dl>";


?>
			</td>
		</tr>
<?php } ?>
	</tbody>
</table>

<?php print $this->paginationControl($this->paginator, 'Sliding', 'SearchPaginationControl.phtml', array('search_params' => $this->searchParams)); ?>

<?php } ?>
