<?php 
	$formParams = array(
							'controller'	=> 'offerings',
							'action'		=> 'search',
							'term'			=> null,
							'department'	=> null,
							'subject'		=> null,
							'division'		=> null,
							'requirement'	=> null,
							'days'			=> null,
							'time_start'	=> null,
							'time_end'		=> null,
							'keywords'		=> null,
							'page'			=> null,
							'submit'		=> null
						);
?>

<form action="<?php print $this->url($formParams); ?>" method="get">
	<table class='search_options'>

		<tr>
			<th>By Term:</th>
			<td>
				<select name="term">
					<option value=''>Any Term</option>
<?php
while ($this->terms->hasNext()) {
	$term = $this->terms->getNextTerm();
	print "\n\t\t\t\t\t<option value='";
	print AbstractCatalogController::getStringFromOsidId($term->getId());
	print "'";
	if (isset($this->selectedTermId) && $term->getId()->isEqual($this->selectedTermId))
		print " selected='selected'";
	print ">".$term->getDisplayName()."</option>";
}
?>
				</select>
			</td>
		</tr>

		<tr>
			<th>By Department:</th>
			<td>
				<select name="department">
					<option value=''>Any Department</option>
<?php
while ($this->departments->hasNext()) {
	$topic = $this->departments->getNextTopic();
	print "\n\t\t\t\t\t<option value='";
	print AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "'";
	if (isset($this->selectedDepartmentId) && $topic->getId()->isEqual($this->selectedDepartmentId))
		print " selected='selected'";
	print ">".$topic->getDisplayName()."</option>";
}
?>
				</select>
			</td>
		</tr>

		<tr>
			<th>Satisfies Requirements:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='requirement_group'>
<?php
$i = 0;
while ($this->requirements->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";
	
	$topic = $this->requirements->getNextTopic();
	print "\n\t\t\t\t<input type='checkbox' name='requirement[]' value='";
	print AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "'";
	foreach ($this->selectedRequirementIds as $selectedId) {
		if ($topic->getId()->isEqual($selectedId)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$topic->getDisplayName()."</label><br/>";
	
	$i++;
}
?>
				</div>
			</td>
		</tr>
		
		<tr>
			<th>Keywords:</th>
			<td>
				<input class='text_input' type='text' name='keywords' value='<?php print $this->keywords; ?>' />
				<div class='help_text'>By default results only have to match one of the supplied keywords. Use a plus (+) before a word to require it or a minus (-) to exclude it. Use an asterisk (*) as a wildcard.</div>
			</td>
		</tr>
		
<?php if (isset($this->searchParams['days'])) { ?>
		<tr>
			<th>Days of the week:</th>
			<td>
				<label><input type='checkbox' name='days[]' value='sunday' <?php if (in_array('sunday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Sunday</label> 
				<label><input type='checkbox' name='days[]' value='monday' <?php if (in_array('monday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Monday</label> 
				<label><input type='checkbox' name='days[]' value='tuesday' <?php if (in_array('tuesday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Tuesday</label> 
				<label><input type='checkbox' name='days[]' value='wednesday' <?php if (in_array('wednesday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Wednesday</label> 
				<label><input type='checkbox' name='days[]' value='thursday' <?php if (in_array('thursday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Thursday</label> 
				<label><input type='checkbox' name='days[]' value='friday' <?php if (in_array('friday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Friday</label> 
				<label><input type='checkbox' name='days[]' value='saturday' <?php if (in_array('saturday', $this->searchParams['days'])) { print "checked='checked'"; } ?> />Saturday</label> 
				<div class='help_text'>Leave all unchecked if no preference.</div>
			</td>
		</tr>
		
		<tr>
			<th>Time:</th>
			<td>
				<label>From 
				<select name='time_start' class='time_select'>
					<option value='0'<?php if (!$this->timeStart) { print  " selected='selected'"; } ?>>Any Time</option>
<?php
	for ($i = 1800; $i < 86400; $i = $i + 1800) {
		print "\n\t\t\t\t\t<option value='$i'";
		if ($this->timeStart == $i)
			print " selected='selected'";
		print ">".AbstractCatalogController::getTimeString($i)."</option>";
	}
?>
				</select> 
				</label>
				
				<label>To 
				<select name='time_end' class='time_select'>
<?php
	for ($i = 1800; $i < 86400; $i = $i + 1800) {
		print "\n\t\t\t\t\t<option value='$i'";
		if ($this->timeEnd == $i)
			print " selected='selected'";
		print ">".AbstractCatalogController::getTimeString($i)."</option>";
	}
?>
				<option value='86400'<?php if ($this->timeEnd == 86400) { print  " selected='selected'"; } ?>>Any Time</option>
				</select> 
				</label>
			</td>
		</tr>
		
		<tr>
			<th>Type:</th>
			<td>
				<div class='help_text'>(Leave all blank for no preference)</div>
				<div class='requirement_group'>
<?php
$i = 0;
while ($this->genusTypes->hasNext()) {
	if (!($i % 5))
		print "\n\t\t\t</div>\n\t\t\t<div class='requirement_group'>";
	
	$type = $this->genusTypes->getNextType();
	print "\n\t\t\t\t<input type='checkbox' name='type[]' value='";
	print AbstractCatalogController::getStringFromOsidType($type);
	print "'";
	foreach ($this->selectedGenusTypes as $selectedType) {
		if ($type->isEqual($selectedType)) {
			print " checked='checked'";
			break;
		}
	}
	print "/><label>".$type->getDisplayName()."</label><br/>";
	
	$i++;
}
?>
				</div>
			</td>
		</tr>


<?php } ?>

		<tr>
			<td colspan='2'><input type='submit' name='submit' value='Search'/>
		</tr>

	</table>
<form>

<?php
/*********************************************************
 * Search results
 *********************************************************/
if (isset($this->paginator)) { 

?>
<h2>Results</h2>

<?php
if (!count($this->paginator)) {
	print "<div class='search_empty'>No Matches</div>";
}

print $this->paginationControl($this->paginator, 'Sliding', 'ItemPaginationControl.phtml', array('search_params' => $this->searchParams)); ?>

<table class='search_results'>
	<tbody>
<?php
	$alternateType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:alternates');
	
	foreach ($this->paginator as $section) { 
		$offeringParams = array(
							'controller'	=> 'offerings',
							'action'		=> 'view',
							'offering'		=> AbstractCatalogController::getStringFromOsidId($section->getId())
						);
		$resourceParams = array(
							'controller'	=> 'resources',
							'action'		=> 'view',
							'offering'		=> null
						);

		$term = $section->getTerm();
		$termUrl = $this->url(array(
						'controller'	=> 'terms',
						'action'		=> 'view',
						'term'			=> AbstractCatalogController::getStringFromOsidId($term->getId()),
						'offering'		=> null
					));
		$topicParams = array(
						'controller'	=> 'topics',
						'action'		=> 'view',
						'offering'		=> null,
						'term'			=> AbstractCatalogController::getStringFromOsidId($term->getId())
					);
		
		// Topics
		$allTopics = AbstractCatalogController::topicListAsArray($section->getTopics());
?>
		<tr>
			<td>
				<a class='title' href='<?php print $this->url($offeringParams); ?>'><?php print $section->getDisplayName(); ?></a>
<?php

if ($section->hasRecordType($alternateType)) {
	$record = $section->getCourseOfferingRecord($alternateType);
	if ($record->hasAlternates()) {
		$alternates = $record->getAlternates();
		print "\n\t\t\t\t<br/>Cross-Listed As:";
		while ($alternates->hasNext()) {
			print "\n\t\t\t\t<br/>";
			$alternate = $alternates->getNextCourseOffering();
			$offeringParams['offering'] = AbstractCatalogController::getStringFromOsidId($alternate->getId());
			print "<a class='title' href=\"".$this->url($offeringParams)."\">";
			print $this->escape($alternate->getDisplayName());
			print "</a> ";
		}
	}
}

print "\n\t<dl>";

print "\n\t\t<dt>Type:</dt>";
print "\n\t\t<dd>".$this->escape($section->getGenusType()->getDisplayName())."</dd>";

print "\n\t\t<dt>Term:</dt>";
print "\n\t\t<dd><a href='".$termUrl."'>".$this->escape($term->getDisplayName())."</a></dd>";

print "\n\t\t<dt>Department:</dt>";
print "\n\t\t<dd>";
$topics = AbstractCatalogController::filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/department"));
foreach ($topics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Requirements Fulfilled:</dt>";
print "\n\t\t<dd>";
$topics = AbstractCatalogController::filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/requirement"));
foreach ($topics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t</dl>";

?>


			</td>
			<td>
				<div class='title'><?php print nl2br($section->getTitle()); ?></div>
				<div class='description'><?php print $section->getDescription(); ?></div>				
<?php
print "\n\t<dl>";
print "\n\t\t<dt>Location:</dt>";
if ($section->hasLocation()) {
	try {
		$locationResource = $section->getLocation();
		print "\n\t\t<dd>";
		$resourceParams['resource'] = AbstractCatalogController::getStringFromOsidId($locationResource->getId());
		print "<a href=\"".$this->url($resourceParams)."\">";
		print $this->escape($locationResource->getDisplayName());
		print "</a> ";
		if ($locationResource->getDescription())
			print "<span class='location_description'>(".$this->escape($locationResource->getDescription()).")</span>";
		print "\n\t\t</dd>";
	} catch (osid_OperationFailedException $e) {
		print "\n\t\t<dd>".$this->escape($section->getLocationInfo())."</dd>";
	}
} else {
	print "\n\t\t<dd>".$this->escape($section->getLocationInfo())."</dd>";
}
print "\n\t\t<dt>Schedule:</dt>";
print "\n\t\t<dd>".nl2br($this->escape($section->getScheduleInfo()))."</dd>";

$instructorsType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:instructors');
if ($section->hasRecordType($instructorsType)) {
	$instructorsRecord = $section->getCourseOfferingRecord($instructorsType);
	print "\n\t\t<dt>Instructors:</dt>";
	print "\n\t\t<dd>";
	$instructors = $instructorsRecord->getInstructors();
	while ($instructors->hasNext()) {
		$instructor = $instructors->getNextResource();
		$resourceParams['resource'] = AbstractCatalogController::getStringFromOsidId($instructor->getId());
		print "<a href=\"".$this->url($resourceParams)."\">";
		print $this->escape($instructor->getDisplayName());
		print "</a> ";
	}
	print "</dd>";
}

// print "\n\t<dt>Subject:</dt>";
// print "\n\t\t<dd>";
// $topics = AbstractCatalogController::filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/subject"));
// foreach ($topics as $topic) {
// 	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
// 	print "<a href=\"".$this->url($topicParams)."\">";
// 	print $this->escape($topic->getDisplayName());
// 	print "</a> ";
// }
// print "</dd>";

// print "\n\t\t<dt>Division:</dt>";
// print "\n\t\t<dd>";
// $topics = AbstractCatalogController::filterTopicsByType($allTopics, new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/division"));
// foreach ($topics as $topic) {
// 	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
// 	print "<a href=\"".$this->url($topicParams)."\">";
// 	print $this->escape($topic->getDisplayName());
// 	print "</a> ";
// }
// print "</dd>";

print "\n\t</dl>";


?>
			</td>
		</tr>
<?php } ?>
	</tbody>
</table>

<?php print $this->paginationControl($this->paginator, 'Sliding', 'SearchPaginationControl.phtml', array('search_params' => $this->searchParams)); ?>

<?php } ?>
