<?php

function printTerm(Zend_View $view, osid_course_Term $term, $label = 'term', $tabs = "\t\t\t") {
	$termUrl = $view->pathAsAbsoluteUrl($view->url(array(
					'controller'	=> 'terms',
					'action'		=> 'view',
					'term'			=> $view->getStringFromOsidId($term->getId()),
					'offering'		=> null
				)));
	
	$start_date = $term->getStartTime()->format('Y-m-d');
	$end_date = $term->getEndTime()->format('Y-m-d');
	$span = $term->getEndTime()->diff($term->getStartTime());
	$weeks = ceil($span->days / 7);
	print "\n".$tabs."<catalog:".$label." id=\"".$view->getStringFromOsidId($term->getId())."\" href=\"".$termUrl."\" start_date=\"".$start_date."\" end_date=\"".$end_date."\" weeks=\"".$weeks."\">";
	print $view->escape($term->getDisplayName());
	print "</catalog:".$label."> ";
}

print '<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:catalog="http://www.middlebury.edu/course_catalog">
	<channel>
		<title>'.$this->feedTitle.'</title>
		<link>'.$this->pathAsAbsoluteUrl($this->url($this->searchParams)).'</link>
		<description></description>
		<lastBuildDate>'.date('r').'</lastBuildDate>
		<generator>Course Catalog</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
';

if (isset($this->previousTerm))
	printTerm($this, $this->previousTerm, 'previous_term', "\t\t");
if (isset($this->term))
	printTerm($this, $this->term, 'chosen_term', "\t\t");
if (isset($this->nextTerm))
	printTerm($this, $this->nextTerm, 'next_term', "\t\t");

	
if (isset($this->terms)) {
	print "\n\t\t<catalog:all_terms>";
	while ($this->terms->hasNext()) {
		printTerm($this, $this->terms->getNextTerm());
	}
	print "\n\t\t</catalog:all_terms>";
}
	
print "\n";

$alternateType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:alternates');

while ($this->sections->hasNext()) { 
	$section = $this->sections->getNextCourseOffering();
	
	$offeringParams = array(
						'controller'	=> 'offerings',
						'action'		=> 'view',
						'offering'		=> $this->getStringFromOsidId($section->getId())
					);
	$resourceParams = array(
						'controller'	=> 'resources',
						'action'		=> 'view',
						'offering'		=> null
					);

	$term = $section->getTerm();
	$topicParams = array(
					'controller'	=> 'topics',
					'action'		=> 'view',
					'offering'		=> null,
					'term'			=> $this->getStringFromOsidId($term->getId())
				);
	
	// Topics
	$allTopics = $this->topicListAsArray($section->getTopics());
?>

		<item>
			<title><?php print $this->escape($section->getDisplayName()); ?></title>
			<link><?php print $this->pathAsAbsoluteUrl($this->url($offeringParams)); ?></link>
			<description><![CDATA[<?php print $section->getDescription(); ?>]]></description>
			<catalog:title><?php print $this->escape($section->getTitle()); ?></catalog:title>
			<catalog:id><?php print $this->escape($this->getStringFromOsidId($section->getId())); ?></catalog:id>
<?php

if ($section->hasRecordType($alternateType)) {
	$record = $section->getCourseOfferingRecord($alternateType);
	if ($record->hasAlternates()) {
		$alternates = $record->getAlternates();
		while ($alternates->hasNext()) {
			$alternate = $alternates->getNextCourseOffering();
			$offeringParams['offering'] = $this->getStringFromOsidId($alternate->getId());
			print "\n\t\t\t<catalog:alternate href=\"".$this->pathAsAbsoluteUrl($this->url($offeringParams))."\">";
			print $this->escape($alternate->getDisplayName());
			print "</catalog:alternate> ";
		}
	}
}

print "\n\t\t\t<catalog:genustype href=\"".$this->pathAsAbsoluteUrl($this->url($offeringParams))."\">";
print $this->escape($section->getGenusType()->getDisplayName());
print "</catalog:genustype> ";

printTerm($this, $term);

$topicType = new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/subject");
$topicTypeString = $this->getStringFromOsidType($topicType);
$topics = $this->filterTopicsByType($allTopics, $topicType);
foreach ($topics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<catalog:topic type=\"".$topicTypeString."\" id=\"".$this->getStringFromOsidId($topic->getId())."\" href=\"".$this->pathAsAbsoluteUrl($this->url($topicParams))."\">";
	print $this->escape($topic->getDisplayName());
	print "</catalog:topic> ";
}

$topicType = new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/department");
$topicTypeString = $this->getStringFromOsidType($topicType);
$topics = $this->filterTopicsByType($allTopics, $topicType);
foreach ($topics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<catalog:topic type=\"".$topicTypeString."\" id=\"".$this->getStringFromOsidId($topic->getId())."\" href=\"".$this->pathAsAbsoluteUrl($this->url($topicParams))."\">";
	print $this->escape($topic->getDisplayName());
	print "</catalog:topic> ";
}

$topicType = new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/requirement");
$topicTypeString = $this->getStringFromOsidType($topicType);
$topics = $this->filterTopicsByType($allTopics, $topicType);
foreach ($topics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<catalog:topic type=\"".$topicTypeString."\" id=\"".$this->getStringFromOsidId($topic->getId())."\" href=\"".$this->pathAsAbsoluteUrl($this->url($topicParams))."\">";
	print $this->escape($topic->getDisplayName());
	print "</catalog:topic> ";
}

$topicType = new phpkit_type_URNInetType("urn:inet:middlebury.edu:genera:topic/level");
$topicTypeString = $this->getStringFromOsidType($topicType);
$topics = $this->filterTopicsByType($allTopics, $topicType);
foreach ($topics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<catalog:topic type=\"".$topicTypeString."\" id=\"".$this->getStringFromOsidId($topic->getId())."\" href=\"".$this->pathAsAbsoluteUrl($this->url($topicParams))."\">";
	print $this->escape($topic->getDisplayName());
	print "</catalog:topic> ";
}


$instructorsType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:instructors');
if ($section->hasRecordType($instructorsType)) {
	$instructorsRecord = $section->getCourseOfferingRecord($instructorsType);
	$instructors = $instructorsRecord->getInstructors();
	while ($instructors->hasNext()) {
		$instructor = $instructors->getNextResource();
		$resourceParams['resource'] = $this->getStringFromOsidId($instructor->getId());
		print "\n\t\t\t<catalog:instructor id=\"".$this->getStringFromOsidId($instructor->getId())."\"  href=\"".$this->pathAsAbsoluteUrl($this->url($resourceParams))."\">";
		print $this->escape($instructor->getDisplayName());
		print "</catalog:instructor> ";
	}
}

if ($section->hasLocation()) {
	try {
		$locationResource = $section->getLocation();
		$resourceParams['resource'] = $this->getStringFromOsidId($locationResource->getId());
		print "\n\t\t\t<catalog:location id=\"".$this->getStringFromOsidId($locationResource->getId())."\" href=\"".$this->pathAsAbsoluteUrl($this->url($resourceParams))."\">";
		print $this->escape($locationResource->getDisplayName());
		print "</catalog:location> ";
// 		if ($locationResource->getDescription())
// 			print "<span class='location_description'>(".$this->escape($locationResource->getDescription()).")</span>";
// 		print "\n\t\t</dd>";
	} catch (osid_OperationFailedException $e) {
		print "\n\t\t\t<catalog:location>".$this->escape($section->getLocationInfo())."</catalog:location>";
	}
} else if ($section->getLocationInfo()) {
	print "\n\t\t\t<catalog:location>".$this->escape($section->getLocationInfo())."</catalog:location>";
}
print "\n\t\t\t<catalog:schedule>".$this->escape($section->getScheduleInfo())."</catalog:schedule>";

$properties = $section->getProperties();
while ($properties->hasNext()) {
	$property = $properties->getNextProperty();
	print "\n\t\t\t<catalog:property>";
	print "\n\t\t\t\t<catalog:display_name>".$property->getDisplayName()."</catalog:display_name>";
	print "\n\t\t\t\t<catalog:display_label>".$property->getDisplayLabel()."</catalog:display_label>";
	print "\n\t\t\t\t<catalog:description><![CDATA[".$property->getDescription()."]]></catalog:description>";
	print "\n\t\t\t\t<catalog:value><![CDATA[".$property->getValue()."]]></catalog:value>";
	print "\n\t\t\t</catalog:property>";
}
?>

		</item>
	<?php } ?>
	</channel>
</rss>
