<?php

print $this->render('schedules/bookmark_control.phtml');

// print "\n\t<div>".$this->escape($this->offering->getDisplayName())."</div>";
print "\n\t<h2>".nl2br($this->escape($this->offering->getTitle()))."</h2>";
if ($this->offering->getDescription())
	print "\n\t<div>".$this->offering->getDescription()."</div>";

$term = $this->offering->getTerm();

$resourceParams = array(
							'controller'	=> 'resources',
							'action'		=> 'view',
							'offering'		=> null,
							'term'			=> $this->getStringFromOsidId($term->getId()),
						);

$termUrl = $this->url(array(
						'controller'	=> 'terms',
						'action'		=> 'view',
						'term'			=> $this->getStringFromOsidId($term->getId()),
						'offering'		=> null
					));
$offeringParams = array(
						'controller' 	=> 'offerings',
						'action'		=> 'view',
						'course'		=> null
					);

print "\n\t<dl class='section_info'>";
print "\n\t\t<dt>Term:</dt>";
print "\n\t\t<dd>";
// print "\n\t\t\t<a href='".$termUrl."'>";
print $this->escape($term->getDisplayName());
// print "</a>";
print "\n\t\t</dd>";
if ($this->offering->hasLocation()) {
	print "\n\t\t<dt>Location:</dt>";
	print "\n\t\t<dd>";
	$locationResource = $this->offering->getLocation();
	$resourceParams['resource'] = $this->getStringFromOsidId($locationResource->getId());
// 	print "<a href=\"".$this->url($resourceParams)."\">";
	print $this->escape($locationResource->getDisplayName());
// 	print "</a> ";
	if ($locationResource->getDescription())
		print "<span class='location_description'>(".$this->escape($locationResource->getDescription()).")</span>";
	print "\n\t\t</dd>";
} else if ($this->offering->getLocationInfo()) {
	print "\n\t\t<dt>Location:</dt>";
	print "\n\t\t<dd>".$this->escape($this->offering->getLocationInfo())."</dd>";
}
print "\n\t\t<dt>Schedule:</dt>";
print "\n\t\t<dd>".$this->formatScheduleInfo($this->offering->getScheduleInfo())."</dd>";
print "\n\t\t<dt>Type:</dt>";
print "\n\t\t<dd>".$this->escape($this->offering->getGenusType()->getDisplayName())."</dd>";

if (!empty($this->instructionMethodTopics)) {
	print "\n\t\t<dt>Course Modality:</dt>";
	print "\n\t\t<dd>";
	foreach ($this->instructionMethodTopics as $topic) {
		$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
		print "<a href=\"".$this->url($topicParams)."\">";
		print $this->escape($topic->getDisplayName());
		print "</a> ";
	}
	print "</dd>";
}

$instructorsType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:instructors');
if ($this->offering->hasRecordType($instructorsType)) {
	$instructorsRecord = $this->offering->getCourseOfferingRecord($instructorsType);
	print "\n\t\t<dt>Instructors:</dt>";
	print "\n\t\t<dd>";
	$instructors = $instructorsRecord->getInstructors();
	while ($instructors->hasNext()) {
		$instructor = $instructors->getNextResource();
		$resourceParams['resource'] = $this->getStringFromOsidId($instructor->getId());
		print "<a href=\"".$this->url($resourceParams)."\">";
		print $this->escape($instructor->getDisplayName());
		print "</a> ";
	}
	print "</dd>";
}
// Topics
$topicParams = array(
						'controller'	=> 'topics',
						'action'		=> 'view',
						'offering'		=> null,
						'term'			=> $this->getStringFromOsidId($term->getId())
					);
print "\n\t<dt>Subject:</dt>";
print "\n\t\t<dd>";
foreach ($this->subjectTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Department:</dt>";
print "\n\t\t<dd>";
foreach ($this->departmentTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Division:</dt>";
print "\n\t\t<dd>";
foreach ($this->divisionTopics as $topic) {
// 	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
// 	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
// 	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Requirements Fulfilled:</dt>";
print "\n\t\t<dd>";
foreach ($this->requirementTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

if (!empty($this->blockTopics)) {
	print "\n\t\t<dt>Additional Details:</dt>";
	print "\n\t\t<dd>";
	foreach ($this->blockTopics as $topic) {
		$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
		print "<a href=\"".$this->url($topicParams)."\">";
		print $this->escape($topic->getDisplayName());
		print "</a> ";
	}
	print "</dd>";
}

if (!empty($this->levelTopics)) {
	print "\n\t\t<dt>Levels:</dt>";
	print "\n\t\t<dd>";
	$i = 0;
	foreach ($this->levelTopics as $topic) {
		if ($i > 0)
			print ", ";
// 		$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
// 		print "<a href=\"".$this->url($topicParams)."\">";
		print $this->escape($topic->getDisplayName());
// 		print "</a> ";
		$i++;
	}
	print "</dd>";
}

if (isset($this->alternates)) {
	$alternateType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:alternates');

	print "\n\t\t<dt>Cross-Listed As:</dt>";
	print "\n\t\t<dd>";
	while ($this->alternates->hasNext()) {
		$alternate = $this->alternates->getNextCourseOffering();
		$offeringParams['offering'] = $this->getStringFromOsidId($alternate->getId());
		print "<a href=\"".$this->url($offeringParams)."\">";
		print $this->escape($alternate->getDisplayName());
		print "</a>";
		if ($alternate->hasRecordType($alternateType)) {
			$alternateRecord = $alternate->getCourseOfferingRecord($alternateType);
			if ($alternateRecord->isPrimary()) {
				print " * ";
			}
		}
		print "<br/>\n\t\t";
	}
	print "</dd>";
}

$availabilityLink = $this->getAvailabilityLink($this->offering);
if (!empty($availabilityLink)) {
	print "\n\t\t<dt>Availability:</dt>";
	print "\n\t\t<dd>";
	print $availabilityLink;
	print "\n\t\t</dd>";
}

print "\n\t</dl>";


print "\n\t<dl class='section_properties'>";
$properties = $this->offering->getProperties();
while ($properties->hasNext()) {
	$property = $properties->getNextProperty();
	print "\n\t\t<dt>";
	print $property->getDisplayName();
	if ($property->getDisplayName() != $property->getDisplayLabel())
		print " (".$property->getDisplayLabel().")";
	print ":</dt>";
	print "\n\t\t<dd>".$property->getValue()."</dd>";
}
print "\n\t</dl>";

print "\n<div class='clear'></div>";

$course = $this->offering->getCourse();
$courseParams = array(
						'controller'	=> 'courses',
						'action'		=> 'view',
						'course'		=> $this->getStringFromOsidId($course->getId()),
						'offering'		=> null
					);
print "\n\t<h2>Course</h2>";
print "\n\t<div><a href='".$this->url($courseParams)."'>".$this->escape($course->getDisplayName())."</a></div>";


if (isset($this->parentOffering)) {
	$offeringParams['offering'] = $this->getStringFromOsidId($this->parentOffering->getId());
	print "\n\t	<h2>Offering</h2>";
print "\n\t\t<div><a href='".$this->url($offeringParams)."'>".$this->escape($section->getDisplayName())."</a></div>";
}
