<?php
// print "\n\t<div>".$this->escape($this->offering->getDisplayName())."</div>";
print "\n\t<h2>\"".$this->escape($this->offering->getTitle())."\"</h2>";
if ($this->offering->getDescription())
	print "\n\t<div>".$this->escape($this->offering->getDescription())."</div>";

$term = $this->offering->getTerm();
$termUrl = $this->url(array(
						'controller'	=> 'terms',
						'action'		=> 'view',
						'term'			=> AbstractCatalogController::getStringFromOsidId($term->getId()),
						'offering'		=> null
					));
print "\n\t<dl>";
print "\n\t\t<dt>Term:</dt>";
print "\n\t\t<dd><a href='".$termUrl."'>".$this->escape($term->getDisplayName())."</a></dd>";
print "\n\t\t<dt>Location:</dt>";
print "\n\t\t<dd>".$this->escape($this->offering->getLocationInfo())."</dd>";
print "\n\t\t<dt>Schedule:</dt>";
print "\n\t\t<dd>".$this->escape($this->offering->getScheduleInfo())."</dd>";
print "\n\t\t<dt>Type:</dt>";
print "\n\t\t<dd>".$this->escape($this->offering->getGenusType()->getDisplayName())."</dd>";

// Topics
$topicParams = array(
						'controller'	=> 'topics',
						'action'		=> 'view',
						'offering'		=> null
					);
print "\n\t<dt>Subject:</dt>";
print "\n\t\t<dd>";
foreach ($this->subjectTopics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Department:</dt>";
print "\n\t\t<dd>";
foreach ($this->departmentTopics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Division:</dt>";
print "\n\t\t<dd>";
foreach ($this->divisionTopics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Requirements Fulfilled:</dt>";
print "\n\t\t<dd>";
foreach ($this->requirementTopics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t</dl>";

$course = $this->offering->getCourse();
$courseParams = array(
						'controller'	=> 'courses',
						'action'		=> 'view',
						'course'		=> AbstractCatalogController::getStringFromOsidId($course->getId()),
						'offering'		=> null
					);
print "\n\t<h2>Course</h2>";
print "\n\t<div><a href='".$this->url($courseParams)."'>".$this->escape($course->getDisplayName())."</a></div>";

$offeringParams = array(	
						'controller' 	=> 'offerings',
						'action'		=> 'view',
						'course'		=> null
					);

if (isset($this->parentOffering)) {
	$offeringParams['offering'] = AbstractCatalogController::getStringFromOsidId($this->parentOffering->getId());
	print "\n\t	<h2>Offering</h2>";
print "\n\t\t<div><a href='".$this->url($offeringParams)."'>".$this->escape($section->getDisplayName())."</a></div>";
}

if (isset($this->otherSections) && $this->otherSections->hasNext()) {
	print "\n\t<h2>Other Sections</h2>";
	while ($this->otherSections->hasNext()) {
		$section = $this->otherSections->getNextCourseOffering();
		if ($section->getId()->isEqual($this->offering->getId()))
			continue;
		$offeringParams['offering'] = AbstractCatalogController::getStringFromOsidId($section->getId());
		print "\n\t<div>";
		if ($this->offering->getId()->isEqual($section->getId())) {
			print $this->escape($section->getDisplayName());
		} else {
			print "<a href='".$this->url($offeringParams)."'>".$this->escape($section->getDisplayName())."</a>";
		}
		print " <em>".$this->escape($section->getGenusType()->getDisplayName())."</em>";
		print "</div>";
	}
}