<?php

print '<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:catalog="http://www.middlebury.edu/course_catalog">
	<channel>
		<title>'.$this->title.'</title>
		<link>'.$this->pathAsAbsoluteUrl($this->url()).'</link>
		<description></description>
		<lastBuildDate>'.date('r').'</lastBuildDate>
		<generator>Course Catalog</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
';

$params = array(	'controller' 	=> 'catalogs',
					'action'		=> 'view');

while ($this->catalogs->hasNext()) {
	$catalog = $this->catalogs->getNextCourseCatalog();
	print "\n\t\t<item>";
	print "\n\t\t\t<title>".$this->escape($catalog->getDisplayName())."</title>";
	$params['catalog'] = $this->getStringFromOsidId($catalog->getId());
	print "\n\t\t\t<link>".$this->pathAsAbsoluteUrl($this->url($params))."</link>";
	print "\n\t\t\t<description><![CDATA[".$catalog->getDescription()."]]></description>";
	print "\n\t\t\t<catalog:id>".$this->getStringFromOsidId($catalog->getId())."</catalog:id>";
	print "\n\t\t</item>";
}


?>

	</channel>
</rss>
