
					<div class="breadcrumb">
						<a href="<?php echo $this->url(array(), null, true) ?>">Search Catalogs</a>
						<?php
						if (!empty($this->menuCatalogSelected)) {
							$searchUrl = $this->url(
								array(
									'controller' => 'catalogs',
									'action' => 'view',
									'catalog' => $this->getStringFromOsidId($this->menuCatalogSelected->getId()),
									'term' => $this->termIdString,
								),
								null,
								true);
							print "\n\t\t\t\t\t\t &raquo; ";
							print "<a class=\"\" href=\"".$searchUrl."\">".$this->escape($this->menuCatalogSelected->getDisplayName())."</a>";

							if (!empty($this->course)) {
								print "\n\t\t\t\t\t\t &raquo; ";
								print $this->escape($this->course->getDisplayName());
							}

							if (!empty($this->offering)) {
								print "\n\t\t\t\t\t\t &raquo; ";
								print $this->escape($this->offering->getDisplayName());
							}
						}
					?>

					</div>
