
								<ul class="menu">
<?php

while ($this->menuCatalogs->hasNext()) {
	$catalog = $this->menuCatalogs->getNextCourseCatalog();
	if (isset($this->menuCatalogSelectedId) && $catalog->getId()->isEqual($this->menuCatalogSelectedId)) {
		print "\n\t\t\t\t\t\t\t\t\t<li class=\"leaf\">";
		print "\n\t\t\t\t\t\t\t\t\t<a class=\"\" href=\"";
		print $this->url(
					array(
						'controller' => 'catalogs',
						'action' => 'view',
						'catalog' => $this->getStringFromOsidId($catalog->getId())),
					null,
					true);
		print "\">".$this->escape($catalog->getDisplayName())."</a>";
		print "\n\t\t\t\t\t\t\t\t\t</li>";
	}
}

?>

								</ul>
