<div class='login_info'>			
<?php
if ($this->isAuthenticationEnabled()) {
	if ($this->isAuthenticated()) {
		print ' <a href="'.$this->url(array('controller' => 'auth', 'action' => 'logout', 'return' => $this->pathAsAbsoluteUrl($this->url()))).'">Log Out</a> ';
		print $this->getUserDisplayName();
	} else {
		print ' <a href="'.$this->url(array('controller' => 'auth', 'action' => 'login', 'return' => $this->pathAsAbsoluteUrl($this->url()))).'">Log In</a>';
	}
}
?>
</div>