<div class='login_info'>			
<?php
if ($this->isAuthenticationEnabled()) {
	$return = $this->pathAsAbsoluteUrl($this->url());
	if (count($_GET))
		$return .= '?'.http_build_query($_GET);

	if ($this->isAuthenticated()) {
		print ' <a href="'.$this->url(array('controller' => 'auth', 'action' => 'logout', 'return' => $return)).'">Log Out</a> ';
		print $this->getUserDisplayName();
	} else {
		print ' <a href="'.$this->url(array('controller' => 'auth', 'action' => 'login', 'return' => $return)).'">Log In</a>';
	}
}
?>
</div>
