
						<ul class="menu">
							<li class="leaf">
								<a href="<?php echo $this->url(array('controller' => 'catalogs', 'action' => 'list'), 'default', true) ?>	">All Catalogs</a>
							</li>

	<?php if ($this->menuCatalogSelected) {
		$searchUrl = $this->url(
			array(
				'controller' => 'offerings',
				'action' => 'search',
				'catalog' => $this->getStringFromOsidId($this->menuCatalogSelected->getId()),
				'term' => $this->termIdString,
			),
			'default',
			true);
	?>
							<li class="expanded">
								<a href="<?php echo $searchUrl; ?>"><?php echo $this->escape($this->menuCatalogSelected->getDisplayName()); ?></a>
								<ul class="menu">
									<li class="leaf<?php if ($this->menuIsSearch) { print " here"; } ?>">
										<a href="<?php echo $searchUrl; ?>" class="<?php if ($this->menuIsSearch) { print " active"; } ?>">Search</a>
									</li>

									<?php
									$config = Zend_Registry::getInstance()->config;
									if (!empty($config->catalog->menu_links)) {
										foreach ($config->catalog->menu_links as $linkSet) {
											if ($this->menuCatalogSelectedId->isEqual(new phpkit_id_URNInetId($linkSet->catalog_id))) {
												if (!empty($linkSet->links)) {
													foreach ($linkSet->links as $link) {
														print "\n\t\t\t\t\t\t\t\t\t<li class=\"leaf\">".$link."</li>";
													}
												}
											}
										}
									}
									?>
								</ul>
							</li>
	 <?php } ?>

	<?php if ($this->isAuthenticationEnabled()) { ?>

							<li class="leaf<?php if ($this->menuIsSchedule) { print " here"; } ?>">
								<a href="<?php echo $this->url(array('controller' => 'schedules', 'catalog' => $this->catalogIdString,
								'term' => $this->termIdString), 'default', true) ?>">My Schedule Planner</a>
							</li>

	<?php } ?>

						</ul>
