						
						<ul class="menu">
							<li class="expanded">
								<a href="<?php echo $this->url(array('controller' => 'catalogs', 'action' => 'list'), null, true) ?>" class="active">Catalogs</a>
								<?php echo $this->render('cataloglist.phtml') ?> 
							</li>

<?php if ($this->catalogIdString) { ?>
						
							<li class="leaf<?php if ($this->menuIsSearch) { print " here"; } ?>">
								<a href="<?php echo $this->url(array('controller' => 'offerings', 'action' => 'search', 'catalog' => $this->catalogIdString, 'term' => $this->termIdString), null, true) ?>" class="<?php if ($this->menuIsSearch) { print " active"; } ?>">Search</a>
							</li>
							
<!-- 
							<li class="leaf<?php if ($this->menuIsTerms) { print " here"; } ?>">
								<a href="<?php echo $this->url(array('controller' => 'terms', 'action' => 'list', 'catalog' => $this->catalogIdString, 'term' => $this->termIdString), null, true) ?>" class="AspNet-Menu-Link">Terms</a>
							</li>
 -->
 	<?php } ?>

 
	<?php if ($this->isAuthenticationEnabled()) { ?>
				
							<li class="leaf<?php if ($this->menuIsSchedule) { print " here"; } ?>">
								<a href="<?php echo $this->url(array('controller' => 'schedules', 'catalog' => $this->catalogIdString,
								'term' => $this->termIdString), null, true) ?>" class="AspNet-Menu-Link">My Schedule Planner &nbsp; <span
								class='beta'>Beta</span></a>
							</li>
		
	<?php } ?>

						</ul>

						
