<?php

$instructorsType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:instructors');
$namesType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:person_names');

print "\n\t<div class='offering_list'>";
if (isset($this->term)) {
	print "\n\t<h2>".$this->offeringsTitle." in ".$this->term->getDisplayName()."</h2>";
	if (isset($this->offeringsForAllTermsUrl)) {
		print "\n\t<div class='all_terms_link'><a href='".$this->offeringsForAllTermsUrl."'>show ".strtolower($this->offeringsTitle)." in all terms</a></div>";
	}
} else {
	print "\n\t<h2>".$this->offeringsTitle."</h2>";
}

$offeringParams = array(	
					'controller' 	=> 'offerings',
					'action'		=> 'view',
					'course'		=> null,
					'topic'			=> null,
					'resource'		=> null
				);
while ($this->offerings->hasNext()) {
	$offering = $this->offerings->getNextCourseOffering();
	if (!isset($currentTerm) || $currentTerm->getId() != $offering->getTermId()) {
		$currentTerm = $offering->getTerm();
		print "\n<h4>".$currentTerm->getDisplayName()."</h4>";
	}
	
	$offeringParams['offering'] = AbstractCatalogController::getStringFromOsidId($offering->getId());
	
	if (isset($this->offering) && $offering->getId()->isEqual($this->offering->getId()))
		print "\n\t<div class='selected_offering'>";
	else
		print "\n\t<div>";
	
	print "<a class='offering_link' href='".$this->url($offeringParams)."'>".$this->escape($offering->getDisplayName())."</a>";
	print " <span class='type'>".$this->escape($offering->getGenusType()->getDisplayName())."</span>";
	
	if (!isset($this->hideOfferingInstructors) || !$this->hideOfferingInstructors) {
		if ($offering->hasRecordType($instructorsType)) {
			$instructorsRecord = $offering->getCourseOfferingRecord($instructorsType);
			$instructors = $instructorsRecord->getInstructors();
			if ($instructors->hasNext()) {
				$instNames = array();
				while ($instructors->hasNext()) {
					$instructor = $instructors->getNextResource();
					if ($instructor->hasRecordType($namesType)) {
						$namesRecord = $instructor->getResourceRecord($namesType);
						$instNames[] = $this->escape($namesRecord->getSurname());
					} else {
						$instNames[] = $this->escape($instructor->getDisplayName());
					}
				}
				print " <span class='instructor'>(";
				print implode(', ', $instNames);
				print ")</span>";
			}
		}
	}
	print "</div>";
}
print "\n\t</div>";