<?php

$instructorsType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:instructors');
$namesType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:person_names');

print "\n\t\t\t<catalog:offering_list>";
$offeringParams = array(	
					'controller' 	=> 'offerings',
					'action'		=> 'view',
					'course'		=> null,
					'topic'			=> null,
					'resource'		=> null
				);
while ($this->offerings->hasNext()) {
	$offering = $this->offerings->getNextCourseOffering();
	$offeringIdString =$this->getStringFromOsidId($offering->getId());
	if (!isset($currentTerm) || $currentTerm->getId() != $offering->getTermId()) {
		if (isset($currentTerm))
			print "\n\t\t\t\t</catalog:offering_term>";
		
		$currentTerm = $offering->getTerm();
		print "\n\t\t\t\t<catalog:offering_term id=\"".$this->getStringFromOsidId($currentTerm->getId())."\" name=\"".$this->escape($currentTerm->getDisplayName())."\">";
	}
	
	$offeringParams['offering'] = $offeringIdString;
	
	print "\n\t\t\t\t\t<catalog:offering";
	print ' id="'.$offeringIdString.'"';
	print ' href="'.$this->url($offeringParams).'"';
	print ">";
	print "\n\t\t\t\t\t\t<catalog:display_name>".$this->escape($offering->getDisplayName())."</catalog:display_name>";
	print "\n\t\t\t\t\t\t<catalog:title>".$this->escape($offering->getTitle())."</catalog:title>";
	print "\n\t\t\t\t\t\t<catalog:description><![CDATA[".$offering->getDescription()."]]></catalog:description>";
	$type = $offering->getGenusType();
	print "\n\t\t\t\t\t\t<catalog:type id=\"".$this->getStringFromOsidType($type)."\">".$this->escape($type->getDisplayName())."</catalog:type>";
	$term = $offering->getTerm();
	print "\n\t\t\t\t\t\t<catalog:term id=\"".$this->getStringFromOsidId($term->getId())."\">".$this->escape($term->getDisplayName())."</catalog:term>";
	print "\n\t\t\t\t\t\t<catalog:location id=\"".$this->getStringFromOsidId($offering->getLocationId())."\">".$this->escape($offering->getLocationInfo())."</catalog:location>";
	print "\n\t\t\t\t\t\t<catalog:schedule>".$this->escape($offering->getScheduleInfo())."</catalog:schedule>";

	if (!isset($this->hideOfferingInstructors) || !$this->hideOfferingInstructors) {
		if ($offering->hasRecordType($instructorsType)) {
			$instructorsRecord = $offering->getCourseOfferingRecord($instructorsType);
			$instructors = $instructorsRecord->getInstructors();
			if ($instructors->hasNext()) {
				$instNames = array();
				while ($instructors->hasNext()) {
					$instructor = $instructors->getNextResource();
					print "\n\t\t\t\t\t\t<catalog:instructor id=\"".$this->getStringFromOsidId($instructor->getId())."\">";
					if ($instructor->hasRecordType($namesType)) {
						$namesRecord = $instructor->getResourceRecord($namesType);
						print "\n\t\t\t\t\t\t\t<catalog:given_name>".$this->escape($namesRecord->getGivenName())."</catalog:given_name>";						print "\n\t\t\t\t\t\t\t<catalog:surname>".$this->escape($namesRecord->getSurname())."</catalog:surname>";
					}
					print "\n\t\t\t\t\t\t\t<catalog:display_name>".$this->escape($instructor->getDisplayName())."</catalog:display_name>";
					
					print "\n\t\t\t\t\t\t</catalog:instructor>";
				}
			}
		}
	}
	print "\n\t\t\t\t\t</catalog:offering>";
}
print "\n\t\t\t\t</catalog:offering_term>";
print "\n\t\t\t</catalog:offering_list>";