#!/usr/bin/env php
<?php

$urls = explode("\n", file_get_contents(__DIR__.'/test-urls.txt'));
$urls = array_map('trim', $urls);
$urls = array_filter($urls, function ($val) { return !empty($val); });

require_once(__DIR__.'/../../vendor/autoload.php');

use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;


$client = new Client([
    'allow_redirects' => false,
    'verify' => false,
]);

$successful = 0;
$failed = 0;
foreach ($urls as $url) {
    try {
        $response = $client->get($url);
        $successful++;
    }
    catch (RequestException $e) {
        $failed++;
        print $url . "\n\t";
        print $e->getCode() . ' ' . $e->getMessage() . "\n";
    }
}
print "\n".count($urls)." URLs tested: $successful succeeded, $failed failed.\n";
