<?php

print '<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:catalog="http://www.middlebury.edu/course_catalog">
	<channel>
		<title>'.$this->escape($this->title).'</title>
		<link>'.$this->pathAsAbsoluteUrl($this->url(array('action' => 'list'))).'</link>
		<description></description>
		<lastBuildDate>'.date('r').'</lastBuildDate>
		<generator>Course Catalog</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
';

$params = array(	'controller' 	=> 'topics',
					'action'		=> 'view',
					'catalog'		=> $this->getStringFromOsidId($this->menuCatalogSelectedId)
	);

$topics = array_merge($this->subjectTopics, $this->departmentTopics, $this->divisionTopics, $this->requirementTopics);
foreach ($topics as $topic) {
	print "\n\t\t<item>";
	print "\n\t\t\t<title>".$this->escape($topic->getDisplayName())."</title>";
	$params['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<link>".$this->pathAsAbsoluteUrl($this->url($params))."</link>";
	print "\n\t\t\t<description><![CDATA[".$topic->getDescription()."]]></description>";
	print "\n\t\t\t<catalog:id>".$this->getStringFromOsidId($topic->getId())."</catalog:id>";
	print "\n\t\t\t<catalog:genustype>".$this->getStringFromOsidType($topic->getGenusType())."</catalog:genustype>";
	print "\n\t\t</item>";
}


?>

	</channel>
</rss>
