<?php

// Topics
$topicParams = array(
						'controller'	=> 'topics',
						'action'		=> 'view',
					);
print "\n\t<h2>Subjects:</h2>";
print "\n\t\t<ul>";
foreach ($this->subjectTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<li>";
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
	print "\n\t\t\t</li>";
}
print "</ul>";

print "\n\t\t<h2>Departments:</h2>";
print "\n\t\t<ul>";
foreach ($this->departmentTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<li>";
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
	print "\n\t\t\t</li>";
}
print "</ul>";

print "\n\t\t<h2>Divisions:</h2>";
print "\n\t\t<ul>";
foreach ($this->divisionTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<li>";
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
	print "\n\t\t\t</li>";
}
print "</ul>";

print "\n\t\t<h2>Requirements Fulfilled:</h2>";
print "\n\t\t<ul>";
foreach ($this->requirementTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "\n\t\t\t<li>";
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
	print "\n\t\t\t</li>";
}
print "</ul>";
