<?php

print "\n\t<h2>Sections</h2>";
$offeringParams = array(	
					'controller' 	=> 'offerings',
					'action'		=> 'view',
					'topic'			=> null
				);
while ($this->offerings->hasNext()) {
	$offering = $this->offerings->getNextCourseOffering();
	$offeringParams['offering'] = $this->getStringFromOsidId($offering->getId());
	print "\n\t<div>";
	print "<a href='".$this->url($offeringParams)."'>".$this->escape($offering->getDisplayName())."</a>";
	print " \"".$this->escape($offering->getTitle())."\" - ";
	print " <em>".$this->escape($offering->getGenusType()->getDisplayName())."</em>";
	print "</div>";
}
