<?php

print "\n<dl>";

print "\n\t<dt>Name</dt>";
print "\n\t<dd>";
print $this->term->getDisplayName();
print "</dd>";

print "\n\t<dt>Start Date</dt>";
print "\n\t<dd>";
print $this->term->getStartTime()->format('Y-m-d');
print "</dd>";

print "\n\t<dt>End Date</dt>";
print "\n\t<dd>";
print $this->term->getEndTime()->format('Y-m-d');
print "</dd>";

print "\n\t<dt>Weeks (including exams)</dt>";
print "\n\t<dd>";
$span = $this->term->getEndTime()->diff($this->term->getStartTime());
print ceil($span->days / 7);
print "</dd>";

print "\n</dl>";
