<?php
header('Content-Type: text/xml');
print '<?xml version="1.0" encoding="utf-8" ?>';

print "\n<term>";

print "\n\t<id>";
print $this->escape($this->getStringFromOsidId($this->term->getId()));
print "</id>";

print "\n\t<name>";
print $this->term->getDisplayName();
print "</name>";

print "\n\t<start_date>";
print $this->term->getStartTime()->format('Y-m-d');
print "</start_date>";

print "\n\t<end_date>";
print $this->term->getEndTime()->format('Y-m-d');
print "</end_date>";

print "\n\t<weeks>";
$span = $this->term->getEndTime()->diff($this->term->getStartTime());
print ceil($span->days / 7);
print "</weeks>";

print "\n</term>";
