<?php

print '<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:catalog="http://www.middlebury.edu/course_catalog">
	<channel>
		<title>'.$this->title.'</title>
		<link>'.$this->pathAsAbsoluteUrl($this->url()).'</link>
		<lastBuildDate>'.date('r').'</lastBuildDate>
		<generator>Course Catalog</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
';

$params = array(	'controller' 	=> 'terms',
					'action'		=> 'view');

while ($this->terms->hasNext()) {
	$term = $this->terms->getNextTerm();
	print "\n\t\t<item>";
	print "\n\t\t\t<title>".$this->escape($term->getDisplayName())."</title>";
	$params['term'] = $this->getStringFromOsidId($term->getId());
	print "\n\t\t\t<link>".$this->pathAsAbsoluteUrl($this->url($params))."</link>";
	print "\n\t\t\t<description><![CDATA[".$term->getDescription()."]]></description>";
	print "\n\t\t\t<catalog:id>".$this->getStringFromOsidId($term->getId())."</catalog:id>";
	print "\n\t\t\t<catalog:start_date>".$term->getStartTime()->format('Y-m-d')."</catalog:start_date>";
	print "\n\t\t\t<catalog:end_date>".$term->getEndTime()->format('Y-m-d')."</catalog:end_date>";
	print "\n\t\t\t<catalog:weeks>".ceil(abs($term->getEndTime()->format('U') - $term->getStartTime()->format('U'))/60/60/24/7)."</catalog:weeks>";
	print "\n\t\t</item>";
}
?>

	</channel>
</rss>
