<?php
print "\n\t\t<article class='course'>";
print "\n\t\t\t<h3>";
print htmlspecialchars($this->course->display_name);
print " ".$this->course->title;
print " (".implode(", ", array_values($this->course->term_strings)).")";
print "</h3> ";
if (empty($this->course->sections)) {
	print "\n\t\t\t<p>".$this->course->description;
	print "\n\t\t\t\t<span class='requirements'>".implode (", ", $this->course->requirements)."</span>";
	print "\n\t\t\t\t<span class='instructors'>".$this->course->instructors."</span>";
	print "\n\t\t\t</p>";
} else {
	foreach ($this->course->sections as $section) {
		print "\n\t\t\t<div class='course_section'>";
		print "\n\t\t\t\t<h4>".$section->term."</h4>";
		print "\n\t\t\t\t<p>".$section->description;
		print "\n\t\t\t\t<span class='requirements'>".implode (", ", $this->course->requirements)."</span>";
		print "\n\t\t\t\t<span class='instructors'>".$section->instructors."</span>";
		print "\n\t\t\t</p>";
	}
}
print "\n\t\t</article>";
