<?php

print '<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:catalog="http://www.middlebury.edu/course_catalog">
	<channel>
		<title>'.$this->escape($this->title).'</title>
		<link>'.$this->pathAsAbsoluteUrl($this->url()).'</link>
		<description></description>
		<lastBuildDate>'.date('r').'</lastBuildDate>
		<generator>Course Catalog</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
';

$courseIdString = $this->getStringFromOsidId($this->course->getId());
$catalogIdString = $this->getStringFromOsidId($this->menuCatalogSelectedId);
print "\n\t\t<item>";

print "\n\t\t\t<title>".$this->escape($this->course->getTitle())."</title>";


$viewUrl = $this->pathAsAbsoluteUrl($this->url(array('controller' => 'courses', 'action' => 'view', 'catalog' => $catalogIdString, 'course' => $courseIdString)));
print "\n\t\t\t<link>".$viewUrl."</link>";
print "\n\t\t\t<guid isPermaLink='true'>".$viewUrl."</guid>";

print "\n\t\t\t<description><![CDATA[";
print $this->course->getDescription();
print "]]></description>";

$topicParams = array(
	'controller' 	=> 'topics',
	'action'		=> 'view',
	'catalog'		=> $catalogIdString,
);
foreach ($this->subjectTopics as $topic) {
	$topicIdString = $this->getStringFromOsidId($topic->getId());
	$topicTypeString = $this->getStringFromOsidType($topic->getGenusType());
	$topicParams['topic'] = $topicIdString;
	print "\n\t\t\t<catalog:topic type=\"".$topicTypeString."\" id=\"".$topicIdString."\" href=\"".$this->pathAsAbsoluteUrl($this->url($topicParams))."\">";
	print $this->escape($topic->getDisplayName());
	print "</catalog:topic> ";
}
foreach ($this->departmentTopics as $topic) {
	$topicIdString = $this->getStringFromOsidId($topic->getId());
	$topicTypeString = $this->getStringFromOsidType($topic->getGenusType());
	$topicParams['topic'] = $topicIdString;
	print "\n\t\t\t<catalog:topic type=\"".$topicTypeString."\" id=\"".$topicIdString."\" href=\"".$this->pathAsAbsoluteUrl($this->url($topicParams))."\">";
	print $this->escape($topic->getDisplayName());
	print "</catalog:topic> ";
}
foreach ($this->requirementTopics as $topic) {
	$topicIdString = $this->getStringFromOsidId($topic->getId());
	$topicTypeString = $this->getStringFromOsidType($topic->getGenusType());
	$topicParams['topic'] = $topicIdString;
	print "\n\t\t\t<catalog:topic type=\"".$topicTypeString."\" id=\"".$topicIdString."\" href=\"".$this->pathAsAbsoluteUrl($this->url($topicParams))."\">";
	print $this->escape($topic->getDisplayName());
	print "</catalog:topic> ";
}

print $this->render('offeringsxml.phtml');

print "\n\t\t</item>";


?>

	</channel>
</rss>
