<?php
// print "\n\t<div>".$this->escape($this->course->getDisplayName())."</div>";
print "\n\t<h2>\"".$this->escape($this->course->getTitle())."\"</h2>";
if ($this->course->getDescription())
	print "\n\t<div>".$this->course->getDescription()."</div>";

// Topics
$topicParams = array(
						'controller'	=> 'topics',
						'action'		=> 'view',
						'offering'		=> null
					);
print "\n\t<dt>Subject:</dt>";
print "\n\t\t<dd>";
foreach ($this->subjectTopics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Department:</dt>";
print "\n\t\t<dd>";
foreach ($this->departmentTopics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Division:</dt>";
print "\n\t\t<dd>";
foreach ($this->divisionTopics as $topic) {
	$topicParams['topic'] = AbstractCatalogController::getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t</dl>";
