<?php
// print "\n\t<div>".$this->escape($this->course->getDisplayName())."</div>";
print "\n\t<h2>".$this->escape($this->course->getTitle())."</h2>";
if ($this->course->getDescription())
	print "\n\t<div>".$this->course->getDescription()."</div>";

print "\n\t<dl class='course_info'>";
// Topics
$topicParams = array(
						'controller'	=> 'topics',
						'action'		=> 'view',
						'offering'		=> null
					);
if (isset($this->term)) {
	$topicParams['term'] = $this->getStringFromOsidId($this->term->getId());
} else if (isset($this->linkTermId)) {
	$topicParams['term'] = $this->getStringFromOsidId($this->linkTermId);
}

print "\n\t<dt>Subject:</dt>";
print "\n\t\t<dd>";
foreach ($this->subjectTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Department:</dt>";
print "\n\t\t<dd>";
foreach ($this->departmentTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Division:</dt>";
print "\n\t\t<dd>";
foreach ($this->divisionTopics as $topic) {
// 	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
// 	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
// 	print "</a> ";
}
print "</dd>";

print "\n\t\t<dt>Requirements Fulfilled:</dt>";
print "\n\t\t<dd>";
foreach ($this->requirementTopics as $topic) {
	$topicParams['topic'] = $this->getStringFromOsidId($topic->getId());
	print "<a href=\"".$this->url($topicParams)."\">";
	print $this->escape($topic->getDisplayName());
	print "</a> ";
}
print "</dd>";

if (isset($this->alternates)) {
	$alternateType = new phpkit_type_URNInetType('urn:inet:middlebury.edu:record:alternates');
	
	print "\n\t\t<dt>Equivalent Courses:</dt>";
	print "\n\t\t<dd>";
	while ($this->alternates->hasNext()) {
		try {
			$alternate = $this->alternates->getNextCourse();
			$altParams['course'] = $this->getStringFromOsidId($alternate->getId());
			print "<a href=\"".$this->url($altParams)."\">";
			print $this->escape($alternate->getDisplayName());
			print "</a>";
			if ($alternate->hasRecordType($alternateType)) {
				$alternateRecord = $alternate->getCourseRecord($alternateType);
				if ($alternateRecord->isPrimary()) {
					print " * ";
				}
			}
			print "<br/>\n\t\t";
		} catch(osid_NotFoundException $e) {
		}
	}
	print "</dd>";
}

print "\n\t</dl>";
