<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Course Catalogs</title>
</head>
<body>
    <h1>Catalogs</h1>
    <?php
    while ($this->catalogs->hasNext()) {
    	$catalog = $this->catalogs->getNextCourseCatalog();
    	print "<h2>".$catalog->getDisplayName()."</h2>";
    }
    ?>
</body>
</html>
