<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for banner_course_CourseManager.
 * Generated by PHPUnit on 2009-04-14 at 15:00:23.
 */
class banner_course_test_CourseManagerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    banner_course_CourseManager
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    	$this->mcugId = new phpkit_id_URNInetId('urn:inet:middlebury.edu:catalog/MCUG');
		$this->manager = $this->sharedFixture['CourseManager'];
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    	
    }

    /**
     * Test that a PDO object is returned
     */
    public function testGetDB()
    {
       $this->assertType('PDO', $this->manager->getDB());
    }

    /**
     * Test that the id Authority is that specified in our test config.
     */
    public function testGetIdAuthority()
    {
       $this->assertEquals('middlebury.edu', $this->manager->getIdAuthority());
    }

    /**
     * Ensure that we cannot initialize the manager again.
     * @expectedException osid_IllegalStateException
     */
    public function testInitialize()
    {
        $this->manager->initialize($this->sharedFixture['RuntimeManager']);
    }

    /**
     * 
     */
    public function testGetCourseLookupSession()
    {
        $this->assertType('osid_course_CourseLookupSession', $this->manager->getCourseLookupSession());
    }

    /**
     * 
     */
    public function testGetCourseLookupSessionForCatalog()
    {
        $this->assertType('osid_course_CourseLookupSession', $this->manager->getCourseLookupSessionForCatalog($this->mcugId));
    }

    /**
     * 
     */
    public function testGetCourseSearchSession()
    {
       $this->assertType('osid_course_CourseSearchSession', $this->manager->getCourseSearchSession());
    }

    /**
     * @todo Implement testGetCourseSearchSessionForCatalog().
     */
    public function testGetCourseSearchSessionForCatalog()
    {
       $this->assertType('osid_course_CourseSearchSession', $this->manager->getCourseSearchSessionForCatalog($this->mcugId));
    }

    /**
     * @todo Implement testGetCourseAdminSession().
     */
    public function testGetCourseAdminSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseAdminSessionForCatalog().
     */
    public function testGetCourseAdminSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseNotificationSession().
     */
    public function testGetCourseNotificationSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseNotificationSessionForCatalog().
     */
    public function testGetCourseNotificationSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogSession().
     */
    public function testGetCourseCatalogSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogAssignmentSession().
     */
    public function testGetCourseCatalogAssignmentSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingLookupSession().
     */
    public function testGetCourseOfferingLookupSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingLookupSessionForCatalog().
     */
    public function testGetCourseOfferingLookupSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingSearchSession().
     */
    public function testGetCourseOfferingSearchSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingSearchSessionForCatalog().
     */
    public function testGetCourseOfferingSearchSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingAdminSession().
     */
    public function testGetCourseOfferingAdminSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingAdminSessionForCatalog().
     */
    public function testGetCourseOfferingAdminSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingNotificationSession().
     */
    public function testGetCourseOfferingNotificationSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingNotificationSessionForCatalog().
     */
    public function testGetCourseOfferingNotificationSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingHierarchySession().
     */
    public function testGetCourseOfferingHierarchySession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingHierarchyDesignSession().
     */
    public function testGetCourseOfferingHierarchyDesignSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingCatalogSession().
     */
    public function testGetCourseOfferingCatalogSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingCatalogAssignmentSession().
     */
    public function testGetCourseOfferingCatalogAssignmentSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermLookupSession().
     */
    public function testGetTermLookupSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermLookupSessionForCatalog().
     */
    public function testGetTermLookupSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermSearchSession().
     */
    public function testGetTermSearchSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermSearchSessionForCatalog().
     */
    public function testGetTermSearchSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermAdminSession().
     */
    public function testGetTermAdminSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermAdminSessionForCatalog().
     */
    public function testGetTermAdminSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermNotificationSession().
     */
    public function testGetTermNotificationSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermNotificationSessionForCatalog().
     */
    public function testGetTermNotificationSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermHierarchySession().
     */
    public function testGetTermHierarchySession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermHierarchyDesignSession().
     */
    public function testGetTermHierarchyDesignSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermCatalogSession().
     */
    public function testGetTermCatalogSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermCatalogAssignmentSession().
     */
    public function testGetTermCatalogAssignmentSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicLookupSession().
     */
    public function testGetTopicLookupSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicLookupSessionForCatalog().
     */
    public function testGetTopicLookupSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicSearchSession().
     */
    public function testGetTopicSearchSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicSearchSessionForCatalog().
     */
    public function testGetTopicSearchSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicAdminSession().
     */
    public function testGetTopicAdminSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicAdminSessionForCatalog().
     */
    public function testGetTopicAdminSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicNotificationSession().
     */
    public function testGetTopicNotificationSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicNotificationSessionForCatalog().
     */
    public function testGetTopicNotificationSessionForCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicHierarchySession().
     */
    public function testGetTopicHierarchySession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicHierarchyDesignSession().
     */
    public function testGetTopicHierarchyDesignSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicCatalogSession().
     */
    public function testGetTopicCatalogSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicCatalogAssignmentSession().
     */
    public function testGetTopicCatalogAssignmentSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogLookupSession().
     */
    public function testGetCourseCatalogLookupSession()
    {
        $this->assertType('osid_course_CourseCatalogLookupSession', $this->manager->getCourseCatalogLookupSession());
    }

    /**
     * @todo Implement testGetCourseCatalogSearchSession().
     */
    public function testGetCourseCatalogSearchSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogAdminSession().
     */
    public function testGetCourseCatalogAdminSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogNotificationSession().
     */
    public function testGetCourseCatalogNotificationSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogHierarchySession().
     */
    public function testGetCourseCatalogHierarchySession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogHierarchyDesignSession().
     */
    public function testGetCourseCatalogHierarchyDesignSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetResourceManager().
     */
    public function testGetResourceManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCalendarManager().
     */
    public function testGetCalendarManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetLearningManager().
     */
    public function testGetLearningManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsVisibleFederation().
     */
    public function testSupportsVisibleFederation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseLookup().
     */
    public function testSupportsCourseLookup()
    {
       $this->assertTrue($this->manager->supportsCourseLookup());
    }

    /**
     * @todo Implement testSupportsCourseSearch().
     */
    public function testSupportsCourseSearch()
    {
        $this->assertTrue($this->manager->supportsCourseLookup());
    }

    /**
     * @todo Implement testSupportsCourseAdmin().
     */
    public function testSupportsCourseAdmin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseNotification().
     */
    public function testSupportsCourseNotification()
    {
         $this->assertFalse($this->manager->supportsCourseNotification());
    }

    /**
     * @todo Implement testSupportsCourseCatalog().
     */
    public function testSupportsCourseCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogAssignment().
     */
    public function testSupportsCourseCatalogAssignment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingLookup().
     */
    public function testSupportsCourseOfferingLookup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingSearch().
     */
    public function testSupportsCourseOfferingSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingAdmin().
     */
    public function testSupportsCourseOfferingAdmin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingNotification().
     */
    public function testSupportsCourseOfferingNotification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingHierarchy().
     */
    public function testSupportsCourseOfferingHierarchy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingHierarchyDesign().
     */
    public function testSupportsCourseOfferingHierarchyDesign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingHierarchySequencing().
     */
    public function testSupportsCourseOfferingHierarchySequencing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingCatalog().
     */
    public function testSupportsCourseOfferingCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingCatalogAssignment().
     */
    public function testSupportsCourseOfferingCatalogAssignment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermLookup().
     */
    public function testSupportsTermLookup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermSearch().
     */
    public function testSupportsTermSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermAdmin().
     */
    public function testSupportsTermAdmin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermNotification().
     */
    public function testSupportsTermNotification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermHierarchy().
     */
    public function testSupportsTermHierarchy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermHierarchyDesign().
     */
    public function testSupportsTermHierarchyDesign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermHierarchySequencing().
     */
    public function testSupportsTermHierarchySequencing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermCatalog().
     */
    public function testSupportsTermCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermCatalogAssignment().
     */
    public function testSupportsTermCatalogAssignment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicLookup().
     */
    public function testSupportsTopicLookup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicSearch().
     */
    public function testSupportsTopicSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicAdmin().
     */
    public function testSupportsTopicAdmin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicNotification().
     */
    public function testSupportsTopicNotification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicHierarchy().
     */
    public function testSupportsTopicHierarchy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicHierarchyDesign().
     */
    public function testSupportsTopicHierarchyDesign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicHierarchySequencing().
     */
    public function testSupportsTopicHierarchySequencing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicCatalog().
     */
    public function testSupportsTopicCatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicCatalogAssignment().
     */
    public function testSupportsTopicCatalogAssignment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogLookup().
     */
    public function testSupportsCourseCatalogLookup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogSearch().
     */
    public function testSupportsCourseCatalogSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogAdmin().
     */
    public function testSupportsCourseCatalogAdmin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogNotification().
     */
    public function testSupportsCourseCatalogNotification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogHierarchy().
     */
    public function testSupportsCourseCatalogHierarchy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogHierarchyDesign().
     */
    public function testSupportsCourseCatalogHierarchyDesign()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogSequencing().
     */
    public function testSupportsCourseCatalogSequencing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseRecordTypes().
     */
    public function testGetCourseRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseRecordType().
     */
    public function testSupportsCourseRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseSearchRecordTypes().
     */
    public function testGetCourseSearchRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseSearchRecordType().
     */
    public function testSupportsCourseSearchRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingRecordTypes().
     */
    public function testGetCourseOfferingRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingRecordType().
     */
    public function testSupportsCourseOfferingRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseOfferingSearchTypes().
     */
    public function testGetCourseOfferingSearchTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseOfferingSearchType().
     */
    public function testSupportsCourseOfferingSearchType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermRecordTypes().
     */
    public function testGetTermRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermRecordType().
     */
    public function testSupportsTermRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTermSearchRecordTypes().
     */
    public function testGetTermSearchRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTermSearchRecordType().
     */
    public function testSupportsTermSearchRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicRecordTypes().
     */
    public function testGetTopicRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicRecordType().
     */
    public function testSupportsTopicRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTopicSearchRecordTypes().
     */
    public function testGetTopicSearchRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsTopicSearchRecordType().
     */
    public function testSupportsTopicSearchRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogRecordTypes().
     */
    public function testGetCourseCatalogRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogRecordType().
     */
    public function testSupportsCourseCatalogRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCourseCatalogSearchRecordTypes().
     */
    public function testGetCourseCatalogSearchRecordTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSupportsCourseCatalogSearchRecordType().
     */
    public function testSupportsCourseCatalogSearchRecordType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
