
			<div class="breadcrumb">
				<?php
				if (!empty($this->breadcrumb)) {
					$i = 0;
					foreach ($this->breadcrumb as  $url => $label) {
						if ($i > 0) {
							print "\n\t\t\t\t\t\t &raquo; ";
						}
						if ( $i < (count($this->breadcrumb) - 1)) {
							print "<a class=\"\" href=\"".$url."\">".$this->escape($label)."</a>";
						} else {
							print $this->escape($label);
						}
						$i++;
					}
				}
				?>

			</div>
