<?php
$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Archive.css'), 'media' => 'all'));
$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/Archive.css'), 'media' => 'all'));

print "\n\t\t<ul class='directory_children'>";
foreach ($this->children as $url => $label) {
	print "\n\t\t\t<li><a href='".$url."'>".$this->escape($label)."</a></li>";
}
print "\n\t\t</ul>";
