<?php
print "\n\t\t<article class='course'>";
print "\n\t\t\t<a name='".$this->course->anchor."' class='local_anchor'></a>"; // Anchor for cross-lists.
print "\n\t\t\t<h3>";
print $this->escape($this->course->display_name);
print " ".$this->escape($this->course->title);
print " (".implode(", ", array_values($this->course->term_strings)).")";
print "</h3> ";
if (empty($this->course->terms)) {
	print "\n\t\t\t<span class='course_description'>".$this->course->description."</span>";
	print "\n\t\t\t<strong class='course_requirements'>".implode (", ", $this->course->requirements)."</strong>";
	print "\n\t\t\t<em class='course_instructors'>".$this->escape($this->course->instructors)."</em>";
} else {
	foreach ($this->course->terms as $term) {
		print "\n\t\t\t<div class='course_term'>";
		print "\n\t\t\t\t<h4>".$this->escape($term->label)."</h4>";
		foreach ($term->sections as $section) {
			print "\n\t\t\t\t<div class='course_section'>";
			if (!empty($section->section_numbers)) {
				print "\n\t\t\t\t\t<div class='course_section_numbers'>Section";
				if (count($section->section_numbers) > 1) {
					print "s";
				}
				print " ".implode(', ', $section->section_numbers);
				print "</div>";
			}
			print "\n\t\t\t\t\t<span class='course_description'>".$section->description."</span>";
			print "\n\t\t\t\t\t<strong class='course_requirements'>".implode (", ", $this->course->requirements)."</strong>";
			print "\n\t\t\t\t\t<em class='course_instructors'>".$this->escape($section->instructors)."</em>";
			print "\n\t\t\t</div>";
		}
		print "\n\t\t\t</div>";
	}
}
if (!empty($this->course->alternates)) {
	print "\n\t\t\t<div class='alternates'>Cross-listed as: ";
	foreach ($this->course->alternates as $alternate) {
		print "\n\t\t\t\t<a class='alternate' href='#".$alternate->anchor."'";
		if ($alternate->is_primary) {
			print " title='Primary course'";
		}
		print ">".$this->escape($alternate->display_name);
		if ($alternate->is_primary) {
			print " <span class='primary_ind'>*</span>";
		}
		print "</a> ";
	}
	print "\n\t\t\t</div>";
}
print "\n\t\t</article>";
