			<span class='course_requirements'>
<?php
$reqs = [];
foreach ($this->requirements as $req) {
	ob_start();
	print "<strong>".$this->escape($req['label'])."</strong>";
	if (!empty($req['req_seats'])) {
		if (count($req['term_seats']) == 1 && $req['req_seats'] != $req['total_seats']) {
			print " (".$this->escape($req['req_seats'])." seats)";
		} elseif (count($req['term_seats'])) {
			$partialSeatsStrings = [];
			$someTermsStrings = [];
			$seatsOnlyPartialInTerm = false;
			$allTermsHaveSeats = true;
			foreach ($req['term_seats'] as $termIdString => $termSeats) {
				if (empty($termSeats['req_seats'])) {
					$allTermsHaveSeats = false;
				} else {
					if ($termSeats['req_seats'] != $termSeats['total_seats']) {
						$seatsOnlyPartialInTerm = true;
					}
					$someTermsStrings[] = $this->escape($termSeats['term_label']);
					$partialSeatsStrings[] = $this->escape($termSeats['term_label']).': '.$this->escape($termSeats['req_seats']).' seats';
				}
			}
			if ($seatsOnlyPartialInTerm) {
				print " (".implode('; ', $termSeatsStrings).")";
			} else if (!$allTermsHaveSeats) {
				print " (".implode('; ', $someTermsStrings).")";
			}
		}
	}
	$reqs[] = ob_get_clean();
}
print implode (", ", $reqs);
?>
			</span>
