<?php $numPerColumn = ceil(count($this->sections)/2); ?>
		<nav class="toc">
			<ul class="toc-list column-1">

<?php
	$inH1 = false;
	$inH2 = false;
	$i = 0;
	$column = 1;
	foreach ($this->sections as $section) {
		$i++;
		switch ($section['type']) {
			case 'h1':
				if (empty($section['toc_text']))
					$title = $section['text'];
				else
					$title = $section['toc_text'];
				if ($inH1) {
					if ($inH2) {
						print "\n\t\t\t\t\t</ul>\n\t\t\t\t";
						$inH2 = false;
					}
					print "</li>";
				}
				$inH1 = true;
				if ($i >= $numPerColumn && $column == 1) {
					print "\n\t\t\t\t</ul>";
					print "\n\t\t\t\t<ul class=\"toc-list column-2\">";
					$column = 2;
				}
				print "\n\t\t\t\t<li><a href='#".$this->textToLink($section['text'])."'>".htmlspecialchars($title)."</a>";
				break;
			case 'h2':
				if (empty($section['toc_text']))
					$title = $section['text'];
				else
					$title = $section['toc_text'];
				if (!$inH2) {
					print "\n\t\t\t\t\t<ul>";
					$inH2 = true;
				}
				print "\n\t\t\t\t\t\t<li><a href='#".$this->textToLink($section['text'])."'>".htmlspecialchars($title)."</a></li>";
				break;
		}
	}
?></li>
			</ul>
			<div class="clearfix"></div>
		</nav>
