<h1>Manage Anti-Requisites</h1>
<p><a href="<?php print $this->url(array('action' => 'index')); ?>">&laquo; Back to Administration</a></p>

<p>Anti-requisites are course-equivalency entries that indicate that a course can't be taken if another already has been. This is in contrast to most usage of equivalency which indicates that courses are the same thing. Anti-requisites listed below will be filtered out of cross-list entries for courses.</p>
<p>Please Note: Any changes made here will affect views for authenticated users immediately, but will not affect catalog archives or anonymous views until the next nightly sync.</p>



<table class='section_admin'>
<thead>
	<tr>
		<th>Subject Code</th>
		<th>Course Number</th>
		<th>Subject Code Equivalent</th>
		<th>Course Number Equivalent</th>
		<th>Date Added</th>
		<th>Added By</th>
		<th>Comments</th>
		<th>Actions</th>
	</tr>
</thead>
<tbody>

<?php
foreach ($this->antirequisites as $antirequisite) {
	print "\n\t<tr>";
	print "\n\t\t<td class='subj_code'>".$antirequisite['subj_code']."</td>";
	print "\n\t\t<td class='crse_numb'>".$antirequisite['crse_numb']."</td>";
	print "\n\t\t<td class='subj_code_eqiv'>".$antirequisite['subj_code_eqiv']."</td>";
	print "\n\t\t<td class='crse_numb_eqiv'>".$antirequisite['crse_numb_eqiv']."</td>";
	print "\n\t\t<td class='added_date'>".$antirequisite['added_date']."</td>";
	print "\n\t\t<td class='added_by'>".$antirequisite['added_by']."</td>";
	print "\n\t\t<td class='comments'>".$antirequisite['comments']."</td>";

	print "\n\t\t<td class='actions'>";
	print "\n\t\t\t<form action='".$this->url()."' method='post'>";
	print "\n\t\t\t<input type='hidden' name='delete' value='delete' />";
	print "\n\t\t\t<input type='hidden' name='subj_code' value='".$antirequisite['subj_code']."' />";
	print "\n\t\t\t<input type='hidden' name='crse_numb' value='".$antirequisite['crse_numb']."' />";
	print "\n\t\t\t<input type='hidden' name='subj_code_eqiv' value='".$antirequisite['subj_code_eqiv']."' />";
	print "\n\t\t\t<input type='hidden' name='crse_numb_eqiv' value='".$antirequisite['crse_numb_eqiv']."' />";
	print "\n\t\t\t<input type='hidden' name='csrf_key' value='".$this->csrf_key."' />";
	print "\n\t\t\t<input type='hidden' name='search_subj_code' value='".$this->search_subj_code."' />";
	print "\n\t\t\t<input type='hidden' name='search_crse_numb' value='".$this->search_crse_numb."' />";
	print "<input type='button' value='Delete'";
	print " onclick='if (confirm(\"Delete ".$antirequisite['subj_code']." ".$antirequisite['crse_numb']." &raquo; ".$antirequisite['subj_code_eqiv']." ".$antirequisite['crse_numb_eqiv']."?\")) {this.form.submit();}'";
	print '/>';
	print "\n\t\t\t</form>";
	print "\n\t\t</td>";
	print "\n\t</tr>";
}
?>
</tbody>
</table>

<a name="add_new"></a>
<h4>Add a new anti-requisite</h4>

<p>Search for a subject code and course number to find related equivalencies.</p>
<form action="<?php echo $this->url(); ?>#add_new" method='post'>
	<label for="search_subj_code">Subject Code: <input type='text' name='search_subj_code' value='<?php echo $this->search_subj_code; ?>' size="4"></label>
	<label for="search_crse_numb">Course Number: <input type='text' name='search_crse_numb' value='<?php echo $this->search_crse_numb; ?>' size="5"></label>
	<input type="submit" name="search" value="Search">
</form>

<?php if (!empty($this->searchResults)): ?>
<form action="<?php echo $this->url(); ?>#add_new" method='post'>
	<table class='section_admin'>
	<thead>
		<tr>
			<th>Add?</th>
			<th>Subject Code</th>
			<th>Course Number</th>
			<th>Subject Code Equivalent</th>
			<th>Course Number Equivalent</th>
			<th>Date Added</th>
			<th>Added By</th>
			<th>Comments</th>
		</tr>
	</thead>
	<tbody>
	<?php
	// var_dump($this->searchResults);
	foreach ($this->searchResults as $eqiv) {
		print "\n\t\t<tr>";
		print "\n\t\t\t<td>";
		if ($eqiv->antirequisite) {
			print "<input type='checkbox' name='already_added' value='".$eqiv->SCREQIV_SUBJ_CODE."/".$eqiv->SCREQIV_CRSE_NUMB."/".$eqiv->SCREQIV_SUBJ_CODE_EQIV."/".$eqiv->SCREQIV_CRSE_NUMB_EQIV."' disabled='disabled' checked='checked'>";
		} else {
			print "<input type='checkbox' name='equivalents_to_add[]' value='".$eqiv->SCREQIV_SUBJ_CODE."/".$eqiv->SCREQIV_CRSE_NUMB."/".$eqiv->SCREQIV_SUBJ_CODE_EQIV."/".$eqiv->SCREQIV_CRSE_NUMB_EQIV."'>";
		}
		print "\n\t\t\t</td>";
		print "\n\t\t\t<td>";
		print $eqiv->SCREQIV_SUBJ_CODE;
		print "\n\t\t\t</td>";
		print "\n\t\t\t<td>";
		print $eqiv->SCREQIV_CRSE_NUMB;
		print "\n\t\t\t</td>";
		print "\n\t\t\t<td>";
		print $eqiv->SCREQIV_SUBJ_CODE_EQIV;
		print "\n\t\t\t</td>";
		print "\n\t\t\t<td>";
		print $eqiv->SCREQIV_CRSE_NUMB_EQIV;
		print "\n\t\t\t</td>";
		print "\n\t\t\t<td>";
		if ($eqiv->antirequisite) {
			print $eqiv->added_date;
		}
		print "\n\t\t\t</td>";
		print "\n\t\t\t<td>";
		if ($eqiv->antirequisite) {
			print $eqiv->added_by;
		}
		print "\n\t\t\t</td>";
		print "\n\t\t\t<td>";
		if ($eqiv->antirequisite) {
			print $this->escape($eqiv->comments);
		} else {
			print "<textarea name='".$eqiv->SCREQIV_SUBJ_CODE."/".$eqiv->SCREQIV_CRSE_NUMB."/".$eqiv->SCREQIV_SUBJ_CODE_EQIV."/".$eqiv->SCREQIV_CRSE_NUMB_EQIV."-comments'></textarea>";
		}
		print "\n\t\t\t</td>";
		print "\n\t\t<tr>";
	}
	?>
	</tbody>
	</table>
	<input type='hidden' name='csrf_key' value='<?php echo $this->csrf_key; ?>' />
	<input type='hidden' name='search_subj_code' value='<?php echo $this->search_subj_code; ?>'>
	<input type='hidden' name='search_crse_numb' value='<?php echo $this->search_crse_numb; ?>'>
	<input type='submit' name='add' value='Mark checked as anti-requisites' />
</form>
<?php endif; ?>
