<?php
	$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Export.css'), 'media' => 'all'));
	$this->headScript()->appendFile($this->baseUrl('javascript/export.js'));
	$this->headScript()->appendFile($this->baseUrl('javascript/jquery-ui-1.12.1/jquery-ui.min.js'));
?>

<h1>Manage Catalog Export Configurations</h1>
<div class='admin-menu'><a href="<?php print $this->url(array('action' => 'index')); ?>">&laquo; Back to Administration</a></div>

<div class='config-menu'>
	<form class='config-select-form' action="<?php print $this->url(); ?>" method="get">
		<select name='config' onchange="this.form.submit();">
			<option value="select">Select a configuration</option>
			<?php
			foreach ($this->configs as $config) {
				print "<option value='".$config['id']."'".(($config == $this->config)?' selected="selected"':'').">".$config['label']."</option>";
			}
			?>
		</select>
	</form>
	<p class='inline-p'> - or - <a href="<?php print $this->url(array('controller' => 'export', 'action' => 'newconfig')); ?>">Create a new configuration</a></p>
</div>

<?php
	print "<div id='config-body'>";

	if($this->catalogId) {
		print "<input id='catalogId' type='hidden' value='" . $this->catalogId . "'></input>";
		print "<input id='configId' type='hidden' value='" . $this->config['id'] . "'></input>";

		print "<div class='error-message error-div'>Error: </div>";

		// Top nav
		print "<button class='link-button' onclick='saveJSON()'>Save</button>";
		print "<button class='link-button' onclick='reset()'>Reset</button>";
		print "<button class='link-button' onclick='deleteConfig(" . $this->config['id'] . ")'>Delete this config</button>";
		print "<button class='link-button' onclick='showHide()'>Show/Hide all groups</button>";
		print "<a class='link-button' href=" . $this->url(array('controller' => 'export', 'action' => 'revisionhistory')) . "?configId=" . $this->config['id'] . ">Revision history</a>";

		// Content
		print "<div><textarea id='note' class='note' style='width:100%' placeholder='(Optional) Write a note about this revision'></textarea></div>";
		print "<ul id='sections-list' class='sections-list'></ul>";
		print "<div class='error-message error-div'>Error: </div>";

		// Bottom nav
		print "<button class='link-button' onclick='saveJSON()'>Save</button>";
		print "<button class='link-button' onclick='reset()'>Reset</button>";
		print "<button class='link-button' onclick='deleteConfig(" . $this->config['id'] . ")'>Delete this config</button>";
		print "<button class='link-button' onclick='showHide()'>Show/Hide all groups</button>";
		print "<a class='link-button' href=" . $this->url(array('controller' => 'export', 'action' => 'revisionhistory')) . "?configId=" . $this->config['id'] . ">Revision history</a>";
	}

	print "</div>";
?>
