<?php
	$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Export.css'), 'media' => 'all'));
	$this->headScript()->appendFile($this->baseUrl('javascript/export.js'));
?>

<h1>Manage Export Configuration</h1>
<div><a href="<?php print $this->url(array('action' => 'index')); ?>">&laquo; Back to Administration</a></div>

<form action="<?php print $this->url(); ?>" method="get">
	<select name='config' onchange="this.form.submit();">
		<option value="select">Select a configuration</option>
<?php
foreach ($this->configs as $config) {
	print "<option value='".$config['label']."'".(($config == $this->config)?' selected="selected"':'').">".$config['label']."</option>";
}
?>
	</select>
</form>

<?php
	if($this->latestRevision) {
		print "<ul class='sections-list'>";
		foreach($this->latestRevisionJsonData as $key => $section) {

			// generate section value input type based on type.
			switch($section['type']) {
				case "h1":
				case "h2":
				case "page_content":
					$sectionInput = "<input value='" . $section['value'] . "'></input>";
					break;
				case "custom_text":
					$sectionInput = "<textarea value='" . $section['value'] . "'>" . $section['value'] . "</textarea>";
					break;
				case "course_list":
					$sectionInput = "
					<select name='course-list-select'>
						<optgroup label='Subjects'>";
						while ($this->subjects->hasNext()) {
							$topic = $this->subjects->getNextTopic();
							$sectionInput .= "<option value='" . $this->getStringFromOsidId($topic->getId()) . "'";
							if (isset($this->selectedDepartmentId) && $topic->getId()->isEqual($this->selectedDepartmentId))
								$sectionInput .= " selected='selected'";
							$sectionInput .= ">" . $this->escape($topic->getDisplayName()) . "</option>";
						}
						$sectionInput .= "
						</optgroup>
						<optgroup label='Departments'>";
						while ($this->departments->hasNext()) {
							$topic = $this->departments->getNextTopic();
							$sectionInput .= "<option value='" . $this->getStringFromOsidId($topic->getId()) . "'";
							if (isset($this->selectedDepartmentId) && $topic->getId()->isEqual($this->selectedDepartmentId))
								$sectionInput .= " selected='selected'";
							$sectionInput .= ">" . $this->escape($topic->getDisplayName()) . "</option>";
						}

						$sectionInput .= "
						</optgroup>
					</select>";
					break;
			}
			print "<li id='" . $key . "' class='section'><span class='section-type'>Type: " . $section['type'] . "</span><span class='section-value'>Value: " . $sectionInput . "</li>";
		}
		print "</ul>";

		// Save and Reset buttons.
		print "<button value='save' onclick='saveJSON()'>Save</button>";
		print "<button value='reset'>Reset</button>";
	}
?>
