<?php
	$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Export.css'), 'media' => 'all'));
	$this->headScript()->appendFile($this->baseUrl('javascript/export.js'));
?>

<h1>Manage Export Configuration</h1>
<div><a href="<?php print $this->url(array('action' => 'index')); ?>">&laquo; Back to Administration</a></div>

<form action="<?php print $this->url(); ?>" method="get">
	<select name='config' onchange="this.form.submit();">
		<option value="select">Select a configuration</option>
<?php
foreach ($this->configs as $config) {
	print "<option value='".$config['label']."'".(($config == $this->config)?' selected="selected"':'').">".$config['label']."</option>";
}
?>
	</select>
</form>

<?php
	print "<div id='config-body'>";

	if($this->catalogId) {
		print "<input id='catalogId' type='hidden' value='" . $this->catalogId . "'></input>";
		print "<input id='configId' type='hidden' value='" . $this->config['id'] . "'></input>";
		print "<button value='save' onclick='saveJSON()'>Save</button>";
		print "<button value='reset' onclick='reset()'>Reset to last save</button>";
		print "<button onclick='newSection(null)'>Add Section</button>";
		print "<ul id='sections-list' class='sections-list'>";
		print "</ul>";
		print "<button value='save' onclick='saveJSON()'>Save</button>";
		print "<button value='reset' onclick='reset()'>Reset to last save</button>";
	}

	print "</div>";

?>
