<?php
	$this->headLink(array('rel' => 'stylesheet', 'href' => $this->baseUrl('/StyleSheets/midd/Export.css'), 'media' => 'all'));
	$this->headScript()->appendFile($this->baseUrl('javascript/schedule.js'));
?>

<h1>Manage Catalog Export Scheduling</h1>
<div class='admin-menu'><a href="<?php print $this->url(array('action' => 'index')); ?>">&laquo; Back to Administration</a></div>

<div class='job-menu'>
	<button value='save' onclick='save()'>Save</button><button value='reset' onclick='reset()'>Reset to last save</button><a class='link-button' href="<?php print $this->url(array('controller' => 'export', 'action' => 'newjob')); ?>">Create a new job</a>
</div>

<div class='job-schedule'>
	<table id='job-table'>
		<tr>
			<th>Active</th>
			<th>Export Path</th>
			<th>Config</th>
			<th>Revision to Export</th>
			<th>Terms</th>
			<th>Actions</th>
		</tr>
	</table>
</div>

<div class='job-menu'>
	<button value='save' onclick='save()'>Save</button><button value='reset' onclick='reset()'>Reset to last save</button><a class='link-button' href="<?php print $this->url(array('controller' => 'export', 'action' => 'newjob')); ?>">Create a new job</a>
</div>
