<ul id="bookmarked_courses">
<?php 
	while ($this->bookmarked_courses->hasNext()) {
		$course = $this->bookmarked_courses->getNextCourse();
		print "\n\t<li class='bookmarked_course'>";
		print "\n\t\t<div class='course_info'>";
		print "\n\t\t\t<a href='".$this->url(array('controller' => 'courses', 'action' => 'view', 'course' => $this->getStringFromOsidId($course->getId())))."' target='_blank'>";
		print $this->escape($course->getDisplayName());
		print " - ".$this->escape($course->getTitle());
		print "</a>";
		print "\n\t\t</div>";

		print "\n\t\t<div class='remove_course'>";
		print "\n\t\t\t<a class='remove_course' title='Remove Course Bookmark' href='".$this->url(array('controller' => 'bookmarks', 'action' => 'remove', 'course' => $this->getStringFromOsidId($course->getId()), 'csrf_key' => $this->csrfKey()))."'>";
		print "\n\t\t\t\t<button>X</button>";
		print "\n\t\t\t</a>";
		print "\n\t\t</div>";
		
		print "\n\t\t<form class='add_to_schedule_form' action='".$this->url(array('action' => 'add', 'term' => $this->termIdString))."' method='post'>";
		print "\n\t\t<select name='schedule_id'>";
		print "\n\t\t\t<option value=''>Add to schedule...</option>";
		foreach ($this->schedules as $schedule) {
			print "\n\t\t\t<option value=\"".$schedule->getId()."\">".$schedule->getName()."</option>";
		}
		print "\n\t\t</select>";
		print "\n\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."' />";
		print "\n\t\t</form>";
		
?>
		<div class="add_section_dialog section_dialog" title="Add which sections?" style='display: none'>
			<form action="<?php print $this->url(array('action' => 'add', 'term' => $this->termIdString)); ?>" class="add_section_form" method="post">
				<div class='section_set' style='display: none'>Choose a group: 
					<select class="section_set" name="section_set">
						<option value='' class='loading'>Loading...</option>
					</select>
				</div>
				
				<div class='section_types'>Choose one option of each type:
					<ul class="section_types">
						<li class='loading'>Loading...</li>
					</ul>
				</div>
				
				<input type='hidden' name='csrf_key' value='<?php print $this->csrfKey(); ?>' />
				<input type='hidden' name='schedule_id' value='' />
				<input type="submit" value="Add Sections"/>
			</form>
			<input type='hidden' name='course_id' value="<?php print $this->getStringFromOsidId($course->getId()); ?>" />
			<input type='hidden' name='section_lookup_url' value='<?php print $this->url(array('action' => 'sectionsforcourse', 'term' => $this->termIdString)); ?>' />
		</div>
		
<?php
		
		print "\n\t</li>";
	}
?>

</ul>

<?php ob_start(); ?>

	$(function() { // on DOM ready 
		
		$("a.remove_course").click(function () {
			if (confirm('Do you want to remove the bookmark for this course?')) {
				var li = $(this).parents('li.bookmarked_course');
				$.ajax({
					url: $(this).attr('href'), 
					success: function () {
						li.remove();
					}
				});
			}
			return false;
		});
		
		
		/*********************************************************
		 * Set up the add-sections dialog controls
		 *********************************************************/
		
		$(".add_section_dialog").each(function () {
			var form = $(this).siblings("form.add_to_schedule_form");
			var addDialog = $(this).dialog({
					autoOpen: false, 
					width:  600, 
					modal: true,
					close: function(event, ui) {
						$(this).find("select.section_set").empty();
					}
				});
			
			form.data("addDialog", addDialog);
		});
		
		$("form.add_to_schedule_form select").change(function () {
			var form = $(this).parent("form");
			var addDialog = form.data("addDialog");
			var scheduleId = $(this).val();
			$(this).val("");
			
			addDialog.find("select.section_set").empty();
			getSectionSets(addDialog, scheduleId);
			addDialog.dialog("open");
		});
		
	});
	
	function getSectionSets (dialog, scheduleId) {
		var lookupUrl = dialog.children("input[name=section_lookup_url]").val();
		var courseId = dialog.children("input[name=course_id]").val();
		
		dialog.find("input[name=schedule_id]").val(scheduleId);
		
		$.getJSON(lookupUrl, {course: courseId, schedule_id: scheduleId}, function (data, textStatus) {
			populateSectionSetSelect(dialog, scheduleId, data);
			populateSectionSets(dialog, scheduleId, dialog.find("select.section_set").val(), data);
		});
	}
	
	function populateSectionSetSelect(dialog, scheduleId, data) {
		var selectList = dialog.find("select.section_set");
		selectList.empty();
		var i = 0;
		for (var linkSetId in data) {
			i++;
			var option = $('<option value="'+linkSetId+'">'+i+'</option>');
			selectList.append(option);
		}
		if (i > 1) {
			dialog.find("div.section_set").show();
		} else {
			dialog.find("div.section_set").hide();
		}

		selectList.data('section_data', data);
		selectList.data('dialog', dialog);
		selectList.data('scheduleId', scheduleId);
		selectList.change(function() {
			populateSectionSets($(this).data('dialog'), $(this).data('scheduleId'), $(this).val(), $(this).data('section_data'));
		});
	}

	function populateSectionSets (dialog, scheduleId, linkSetId, data) {

		var setsList = dialog.find("ul.section_types");
		setsList.empty();
		var i = 0;
		for (var linkTypeId in data[linkSetId]) {
			var sectionSet = data[linkSetId][linkTypeId];
			
			var setListItem = $('<li></li>');
			setsList.append(setListItem);
			var setList = $('<ul class="section_set"></ul>');
			setListItem.append(setList);
			
			for (var j = 0; j < sectionSet.length; j++) {
				var section = sectionSet[j];
				
				var item = $('<li class="section"></li>');
				setList.append(item);
				var radio = $('<input type="radio" name="section_group_'+i+'" value="'+section.id+'"/>');
				item.append(radio);
				if (section.selected) {
					radio.attr('checked', 'checked');
				}
				item.append(' ');
				item.append(section.name);
				item.append(' <div class="section_instructor section_info"><span class="section_type">'+section.type+'</span> - <span class="section_instructor">'+section.instructor+'</span></div>');
				item.append('');
				if (section.conflicts) {
					var conflictsClass = ' conflicting';
					var conflictNames = '<br/> &nbsp; &nbsp; ' + section.conflictString;
				} else {
					var conflictsClass = '';
					var conflictNames = '';
				}
				item.append('<div class="section_time section_info'+conflictsClass+'">'+section.schedule+conflictNames+'</div>');
				item.append('<div class="section_location section_info">'+section.location+'</div>');
			}

			i++;
		}
	}

<?php 

$this->headScript()->appendScript(ob_get_clean());
