				<select name="catalog">
					<option value='<?php print $this->url(array('catalog' => NULL, 'term' => NULL)); ?>'>All Catalogs</option>
<?php
while ($this->catalogs->hasNext()) {
	$catalog = $this->catalogs->getNextCourseCatalog();
	print "\n\t\t\t\t\t<option value='";
	print $this->url(array('catalog' => $this->getStringFromOsidId($catalog->getId()), 'term' => NULL));
	print "'";
	if (isset($this->menuCatalogSelectedId) && $catalog->getId()->isEqual($this->menuCatalogSelectedId))
		print " selected='selected'";
	print ">".$catalog->getDisplayName()."</option>";
}
?>
				</select>