<?php

$offerings = $this->schedule->getOfferings();

if (!count($offerings)) {
	return;
}
print "\n\t\t<table style='border: 0px; width: 100%; font-size: 12px;'>";
foreach ($offerings as $offering) {
	print "\n\t\t\t<tr>";

	print "\n\t\t<td style='border-top: 1px dotted; vertical-align: top; white-space: nowrap;'>";
	print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
	print $this->escape($offering->getDisplayName());
	print "</a></br>CRN: ".$this->escape($offering->getCourseReferenceNumber());
	print "\n\t\t</td>";

	print "\n\t\t<td style='border-top: 1px dotted; vertical-align: top; white-space: nowrap;'>";
	print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
	print nl2br($this->escape($offering->getTitle()));
	print "</a>";
	print "\n\t\t</td>";

	print "\n\t\t<td style='border-top: 1px dotted; vertical-align: top;";
	if ($this->schedule->hasCollisions($offering->getId()))
		print ' color: red;';
	print "'>".$this->formatScheduleInfo($offering->getScheduleInfo())."</td>";
	print "\n\t\t<td style='border-top: 1px dotted; vertical-align: top;'>".nl2br($this->escape($offering->getLocationInfo()))."</td>";

	print "\n\t\t\t</tr>";
}
print "\n\t\t</table>";
