<?php
$this->headScript()->appendScript("
	$(function() { // on DOM ready

		$('#schedules_term_choice select').change(function () {
			window.location = $(this).val();
		});

	});
");
$this->headTitle('Schedule Planner');
?>

<table class='schedule_planner'>
	<thead>
		<tr>
			<td colspan='2'>
				<form action='#' method='get' id='schedules_term_choice'>
					<?php print $this->render('schedules/catalog_select.phtml'); ?>
					<?php print $this->render('schedules/term_select.phtml'); ?>
				</form>
			</td>
		</tr>
		<tr>
			<th>Saved Courses in <?php print $this->render('schedules/selected_term_name.phtml'); ?></th>
			<th>Schedules for <?php print $this->render('schedules/selected_term_name.phtml'); ?></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td id='bookmarks_column'>
				<?php print $this->render('schedules/bookmarks.phtml'); ?>
			</td>
			<td id='schedules_column'>
				<?php print $this->render('schedules/schedules.phtml'); ?>
			</td>
		</tr>
	</tbody>
</table>
