<?php

/*********************************************************
 * Figure out how many days we are working with.
 *********************************************************/
$hasSunday = false;
$hasSaturday = false;
foreach ($this->events as $event) {
	if ($event['dayOfWeek'] == 0)
		$hasSunday = true;
	if ($event['dayOfWeek'] == 6)
		$hasSaturday = true;
}
$numDays = 7;
$startDay = 0;
$endDay = 6;
if (!$hasSunday) {
	$numDays--;
	$startDay = 1;
}
if (!$hasSaturday) {
	$numDays--;
	$endDay = 5;	
}


/*********************************************************
 * Set up our image.
 *********************************************************/

$width = 910;
if ($this->width)
	$width = $this->width;
$height = 800;
if ($this->height)
	$height = $this->height;

$fontFile = "/usr/share/fonts/bitstream-vera/Vera.ttf";

$im = ImageCreateTrueColor($width, $height);

// Set colors
$black = ImageColorAllocate($im, 0, 0, 0); 
$white = ImageColorAllocate($im, 255, 255, 255); 
$orange = ImageColorAllocate($im, 255, 200, 0); 
$yellow = ImageColorAllocate($im, 255, 255, 0); 
$tan = ImageColorAllocate($im, 255, 255, 190); 
$ltgrey = ImageColorAllocate($im, 235, 235, 235); 
$grey = ImageColorAllocate($im, 200, 200, 200); 
$dkgrey = ImageColorAllocate($im, 140, 140, 140);
$blue = ImageColorAllocate($im, 0, 90, 207);
$red = ImageColorAllocate($im, 255, 50, 50);
$darkred = ImageColorAllocate($im, 0, 0, 0);
$ltblue = ImageColorAllocate($im, 175, 210, 255);


// Background color
imagefilledrectangle($im, 0, 0, $width, $height, $white);

$timeWidth = 97;
$gridWidth = $width - $timeWidth;
$dayWidth = floor($gridWidth / $numDays);

$firstHour = floor($this->minTime/3600);
$gridStartTime = $firstHour * 3600;
$hoursToShow = ceil(($this->maxTime - $this->minTime)/3600);

$headerHeight = 48;
$gridHeight = $height - $headerHeight;
$hourHeight = floor($gridHeight / $hoursToShow);

// header row & time column
imagefilledrectangle($im, 1, 1, $width - 2, $headerHeight - 1, $ltgrey);
imagefilledrectangle($im, 1, 1, $timeWidth - 1, $height - 2, $ltgrey);

// Hours
for ($h = 0; $h < $hoursToShow; $h++) {
	$top = $headerHeight + ($hourHeight * $h);
	$bottom = $top + $hourHeight;
	imagerectangle($im, 0, $top, $width, $bottom, $grey);
}

// Days
for ($d = $startDay; $d < $numDays; $d++) {
	$left = $timeWidth + ($dayWidth * $d);
	$right = $left + $dayWidth;
	imagerectangle($im, $left, 0, $right, $height, $black);
}

// Day Labels
$days = array('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat');
for ($d = $startDay; $d <= $endDay; $d++) {
	$label = $days[$d];
	
	$dayPosition = $d - $startDay;
	$left = $timeWidth + ($dayWidth * $dayPosition);
	$size = 24;
	$bb = imagettfbbox($size, 0, $fontFile, $label);
	$textWidth = $bb[2] - $bb[0];
	ImageTTFText($im, $size, 0, $left + (($dayWidth - $textWidth)/2), $headerHeight - 5, $black, $fontFile, $label); 
}

// Hour Labels
for($i = 0; $i < $hoursToShow; $i++) {
	$hour = $firstHour + $i;
	if ($hour < 12)
		$hourString = $hour.':00 am';
	else if ($hour == 12)
		$hourString = '12:00 pm';
	else
		$hourString = ($hour - 12).':00 pm';
	
	$size = 12;
	$bb = imagettfbbox($size, 0, $fontFile, $hourString);
	$textWidth = $bb[2] - $bb[0];
	$textHeight = $bb[1] - $bb[5];
	$top = $headerHeight + ($hourHeight * $i) + $textHeight + intval(($hourHeight - $textHeight)/2);
	$left = $timeWidth - $textWidth - 10;
	ImageTTFText($im, $size, 0, $left, $top, $black, $fontFile, $hourString); 
}

/*********************************************************
 * Events
 *********************************************************/

foreach ($this->events as $event) {
	if ($event['collisions']) {
		$eventColor = $red;
		$eventBorderColor = $darkred;
	} else {
		$eventColor = $ltblue;
		$eventBorderColor = $blue;
	}
	$dayPosition = $event['dayOfWeek'] - $startDay;
	$left = $timeWidth + ($dayWidth * $dayPosition) + 1;		// 1px margin
	$right = $left + $dayWidth - 2;	// 1px margin
	
	$top = timePosition($gridStartTime, $hourHeight, $event['startTime']) + $headerHeight;
	$bottom = timePosition($gridStartTime, $hourHeight, $event['endTime']) + $headerHeight;
	
	imagefilledrectangle($im, $left, $top, $right, $bottom, $eventColor);
	imagerectangle($im, $left, $top, $right, $bottom, $eventBorderColor);
	
	$start = Time::withSeconds($event['startTime']);
	$end = Time::withSeconds($event['endTime']);
	$string = $start->hour12().':'.str_pad($start->minute(), 2, '0', STR_PAD_LEFT).'-'.$end->hour12().':'.str_pad($end->minute(), 2, '0', STR_PAD_LEFT);
	$size = 10;
	$bb = imagettfbbox($size, 0, $fontFile, $string);
	$textWidth = $bb[2] - $bb[0];
	$textHeight = $bb[1] - $bb[5];
	$textTop = $top + $textHeight + 3;
	$textLeft = $left + (($dayWidth - $textWidth)/2);
	ImageTTFText($im, $size, 0, $textLeft, $textTop, $black, $fontFile, $string);
	
	$size = 10;
	$bb = imagettfbbox($size, 0, $fontFile, $event['name']);
	$textWidth = $bb[2] - $bb[0];
	$textHeight = $bb[1] - $bb[5];
	$textTop = $top + $textHeight + 16;
	$textLeft = $left + (($dayWidth - $textWidth)/2);
	ImageTTFText($im, $size, 0, $textLeft, $textTop, $black, $fontFile, $event['name']);
	
	$size = 10;
	$bb = imagettfbbox($size, 0, $fontFile, $event['location']);
	$textWidth = $bb[2] - $bb[0];
	$textHeight = $bb[1] - $bb[5];
	$textTop = $top + $textHeight +$textHeight + 20;
	$textLeft = $left + (($dayWidth - $textWidth)/2);
	ImageTTFText($im, $size, 0, $textLeft, $textTop, $black, $fontFile, $event['location']);

}

function timePosition($gridStartTime, $hourHeight, $time) {
	$diff = $time - $gridStartTime;
	$hours = $diff/3600;
	return round($hours * $hourHeight);
}


/*********************************************************
 * Final Outlines.
 *********************************************************/

// Background Outline
imagerectangle($im, 0, 0, $width - 1, $height - 1, $black);
// Header & time outlines
imagerectangle($im, 0, 0, $width, $headerHeight, $black);
imagerectangle($im, 0, 0, $timeWidth, $height, $black);

imagepng($im, null, 5);