<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
		"http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>
<head>
	<title><?php print $this->escape($this->schedule->getName()); ?></title>

	<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/base/jquery-ui.css" type="text/css" media="all" />

	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js"></script>

	<link rel="stylesheet" media="all" type="text/css" href="<?php echo $this->url(array(), null, true) ?>2d/StyleSheets/CatalogStyles.css" />


	<link rel="stylesheet" type="text/css" href="<?php print $this->url(array(), null, true).'javascript/jquery-week-calendar/jquery.weekcalendar.css'; ?>"/>
	<style type="text/css">
		div.wc-toolbar {display: none;}
		.wc-time-slots .wc-today { background-color: #FFF; }
		.wc-header .wc-today { font-weight: normal; }
	</style>

	<script type="text/javascript" src="<?php print $this->url(array(), null, true).'javascript/jquery-week-calendar/libs/date.js'; ?>"></script>
	<script type="text/javascript" src="<?php print $this->url(array(), null, true).'javascript/jquery-week-calendar/jquery.weekcalendar.js'; ?>"></script>
	<script type="text/javascript" src="<?php print $this->url(array(), null, true).'javascript/schedule.js'; ?>"></script>

	<script type="text/javascript">
	// <![CDATA[

		$(function() { // on DOM ready

			renderSchedule($("#calendar"), $('#calendar input[name=jsonUrl]').val(), 13, 11);

		});

	// ]]>
	</script>


	<style type="text/css">
		div.schedule li.offering div.offering_name {
			width: 120px;
		}
		div.schedule li.offering div.offering_title {
			width: 250px;
			height: 3em;
		}

		div.schedule li.offering div.location, div.schedule li.offering div.time div.crn {
			white-space: nowrap;
		}

		div.schedule li.offering {
			border-top: 1px dotted;
			padding: 5px;
			list-style-type: none;
		}
		div.schedule ul {
			padding: 5px;
			page-break-inside: avoid;
		}

		.wc-cal-event {
			color: #000;
		}

		body {
			font-size: 12px;
		}

		div.schedule {
			border: none;
		}

	</style>
</head>
<?php

$offerings = $this->schedule->getOfferings();

$numHours = $this->schedule->getLatestHour() - $this->schedule->getEarliestHour() + 1;
$numOfferings = count($offerings);
$hourHeight = $numHours * 13 * 4;
$offeringHeight = $numOfferings * 40;

?>
<body>

<div class='schedule'>

<h1><?php print $this->escape($this->schedule->getName()); ?></h1>
<!-- <?php print ' &nbsp; '.($hourHeight);  print ' + '.($offeringHeight); print ' = '.($offeringHeight + $hourHeight); ?>
 -->

<div id='calendar' title="<?php print $this->escape($this->schedule->getName()); ?>">
	<input type='hidden' name='jsonUrl' value="<?php print $this->url(array('action' => 'eventsjson', 'schedule_id' => $this->schedule->getId())); ?>"/>
	<input type='hidden' name='start_hour' value="<?php print ($this->schedule->getEarliestHour()); ?>"/>
	<input type='hidden' name='end_hour' value="<?php print ($this->schedule->getLatestHour() + 1); ?>"/>
	<input type='hidden' name='show_sunday' value="<?php print (($this->schedule->hasEventsOnSunday())?'yes':'no'); ?>"/>
	<input type='hidden' name='show_saturday' value="<?php print (($this->schedule->hasEventsOnSaturday())?'yes':'no'); ?>"/>
</div>

<?php

print "\n\t\t<ul";
if (($hourHeight + $offeringHeight) > 630) {
	print " style='page-break-before: always;'";
}
print ">";

if (!count($offerings)) {
	print "\n\t\t\t<li style='visibility: hidden'> &nbsp; </li>";
}
foreach ($offerings as $offering) {
	print "\n\t\t\t<li class='offering'>";

	print "\n\t\t<div class='offering_name'>";
	print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
	print $this->escape($offering->getDisplayName());
	print "</a>";
	print "\n\t\t</div>";

	print "\n\t\t<div class='separator'> - </div>";

	print "\n\t\t<div class='offering_title'>";
	print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
	print nl2br($this->escape($offering->getTitle()));
	print "</a>";
	print "\n\t\t</div>";

	print "\n\t\t<div class='crn'>CRN: ".$this->escape($offering->getCourseReferenceNumber())."</div>";

	print "\n\t\t<div class='time";
	if ($this->schedule->hasCollisions($offering->getId()))
		print ' conflicting';
	print "'>".$this->formatScheduleInfo($offering->getScheduleInfo())."</div>";
	print "\n\t\t<div class='location'>".nl2br($this->escape($offering->getLocationInfo()))."</div>";

	print "\n\t\t\t</li>";
}
print "\n\t\t</ul>";

?>
</div>

</body>
</html>
