<?php

// Remove/Change Dialog.
print "\n\t\t<div title='Remove or Change Sections' class='remove_dialog'>";
print "<p>What do you want to do?</p>";

// Change form
$scheduleTermIdString = $this->getStringFromOsidId($this->schedule->getTermId());
?>
<button class='change_sections_button'>Change sections</button>
<div class="change_section_dialog section_dialog" title="Include which sections?" style='display: none'>
	<form action="<?php print $this->url(array('action' => 'add', 'term' => $scheduleTermIdString)); ?>" class="add_section_form" method="post">
		
		<div class='section_set' style='display: none'>Choose a group: 
			<select class="section_set" name="section_set">
				<option value='' class='loading'>Loading...</option>
			</select>
		</div>
		
		<div class='section_types'>Choose one option of each type:
			<ul class="section_types">
				<li class='loading'>Loading...</li>
			</ul>
		</div>
		
		<input type='hidden' name='csrf_key' value='<?php print $this->csrfKey(); ?>' />
		<input type='hidden' name='schedule_id' value='<?php print $this->schedule->getId(); ?>' />
		<input type="submit" value="Save Changes"/>
	</form>
	<input type='hidden' name='course_id' value="<?php print $this->getStringFromOsidId($this->offering->getCourseId()); ?>" />
	<input type='hidden' name='section_lookup_url' value='<?php print $this->url(array('action' => 'sectionsforcourse', 'term' => $scheduleTermIdString)); ?>' />
</div>

<?php

// Remove Form
print "\n\t\t<form class='remove_offering_form' action='".$this->url(array('action' => 'remove'))."' method='post'>";
print "\n\t\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."'/>";
print "\n\t\t\t<input type='hidden' name='schedule_id' value='".$this->schedule->getId()."'/>";
print "\n\t\t\t<input type='hidden' name='offering' value='".$this->getStringFromOsidId($this->offering->getId())."'/>";
print "\n\t\t\t<input type='submit' value='Remove all sections of ".$this->escape($this->offering->getCourse()->getDisplayName())."'/>";
print "\n\t\t</form>";

// Cancel
print "\n\t\t<button class='cancel'>Cancel</button>";

print "\n\t\t</div>";

// Remove/Change Button.
print "\n\t\t<button class='remove_button' title='Remove or Change Sections'>X</button>";



if (!defined('REMOVE_OFFERING_DIALOG_JS_ADDED')) {
	ob_start();
?>

	$(function() { // on DOM ready 
		
		/*********************************************************
		 * Remove dialog controls
		 *********************************************************/
		$(".remove_dialog").each(function() {
			var button = $(this).siblings(".remove_button");
			var removeDialog = $(this).dialog({
					autoOpen: false, 
					width:  600, 
					modal: true,
					position: 'top'
				});
			
			button.data("removeDialog", removeDialog);
		});
		
		$(".remove_button").click(function(){
			var removeDialog = $(this).data('removeDialog');
			removeDialog.dialog("open");
		});
		
		$(".remove_dialog .cancel").click(function() {
			$(this).parent().dialog('close');
		});
		
		$(".change_section_dialog").each(function () {
			var button = $(this).siblings(".change_sections_button");
			var addDialog = $(this).dialog({
					autoOpen: false, 
					width:  600, 
					modal: true,
					close: function(event, ui) {
						$(this).find("ul.section_sets").empty();
					}
				});
			
			button.data("addDialog", addDialog);
		});
		
		$(".change_sections_button").click(function () {
			var removeDialog = $(this).parent();
			removeDialog.dialog("close");
			
			var addDialog = $(this).data("addDialog");
			var scheduleId = addDialog.find("input[name=schedule_id]").val();
						
			addDialog.find("ul.section_sets").empty();
			getSectionSets(addDialog, scheduleId);
			addDialog.dialog("open");
		});
		
	});


<?php

	$this->headScript()->appendScript(ob_get_clean());
	define('REMOVE_OFFERING_DIALOG_JS_ADDED', true);
}