<?php

print "\n\t<a class='calendar_button' href='".$this->url(array('action' => 'eventsjson', 'schedule_id' => $this->schedule->getId()))."' title='Click to zoom'>";
print "\n\t<img class='calendar_img' src='".$this->url(array('action' => 'png', 'schedule_id' => $this->schedule->getId()))."' alt='Weekly Schedule Image'/>";
print "\n\t\t</a>";

print "\n\t<div class='calendar' style='display: none;' title=\"".$this->escape($this->schedule->getName())."\">";
print "\n\t\t<input type='hidden' name='start_hour' value='".($this->schedule->getEarliestHour())."'/>";
print "\n\t\t<input type='hidden' name='end_hour' value='".($this->schedule->getLatestHour() + 1)."'/>";
print "\n\t\t<input type='hidden' name='show_sunday' value='".(($this->schedule->hasEventsOnSunday())?'yes':'no')."'/>";
print "\n\t\t<input type='hidden' name='show_saturday' value='".(($this->schedule->hasEventsOnSaturday())?'yes':'no')."'/>";
print "</div>";


if (!defined('CALENDAR_DIALOG_JS_ADDED')) {
	ob_start();
?>

	$(function() { // on DOM ready

		/*********************************************************
		 * Calendar controls
		 *********************************************************/
		<?php
		$this->headLink()->appendStylesheet($this->url(array(), null, true).'javascript/jquery-week-calendar/jquery.weekcalendar.css');
		$this->headStyle()->appendStyle('
			div.wc-toolbar {display: none;}
			.wc-time-slots .wc-today { background-color: #FFF; }
			.wc-header .wc-today { font-weight: normal; }
		');
		$this->headScript()->appendFile($this->url(array(), null, true).'javascript/jquery-week-calendar/libs/date.js');
		$this->headScript()->appendFile($this->url(array(), null, true).'javascript/jquery-week-calendar/jquery.weekcalendar.js');
		$this->headScript()->appendFile($this->url(array(), null, true).'javascript/schedule.js');

		?>

		$(".calendar").each(function() {
			var button = $(this).siblings(".calendar_button");
			var calendar = $(this).dialog({
					autoOpen: false,
					width:  900,
					modal: true,
					position: 'top'
				});

			button.data("calendar", calendar);
		});
		$(".calendar_button").click(function(){
			var jsonUrl = $(this).attr('href');
			var calendar = $(this).data('calendar');
			calendar.dialog("open");

			if (!calendar.data('initialized')) {
				renderSchedule(calendar, jsonUrl);
				calendar.data('initialized', true);
			}

			return false;
		});

	});


<?php

	$this->headScript()->appendScript(ob_get_clean());
	define('CALENDAR_DIALOG_JS_ADDED', true);
}
