	<a class='email_button' href='#' title='Click for print view.'><button>EMail</button></a>

	<div class='email_dialog' style='display: none;' title="<?php print $this->escape($this->schedule->getName()); ?>">
		<p class='notice'><strong>This feature is not yet operational. Please check back in a few days.</strong></p>

		<form action='<?php print $this->url(array('action' => 'email')); ?>' method='post'>
			<label for='from-<?php print $this->schedule->getId(); ?>'>From: </label>
			<input id='from-<?php print $this->schedule->getId(); ?>' name='from' type='text' value='<?php print $this->getUserDisplayName(); ?> &lt;<?php print $this->getUserEmail(); ?>&gt;' readonly='readonly' size='42'/>
			
			<br/><label for='to-<?php print $this->schedule->getId(); ?>'>To: </label>
			<input id='to-<?php print $this->schedule->getId(); ?>' name='to' type='text' size='42'/>
			
			<br/><label for='subject-<?php print $this->schedule->getId(); ?>'>Subject:</label>
			<input id='subject-<?php print $this->schedule->getId(); ?>' name='subject' type='text' value="<?php print $this->escape($this->schedule->getName()); ?>" size='42'/>
			
			<br/><label for='message-<?php print $this->schedule->getId(); ?>'> &nbsp; </label>
			<textarea id='message-<?php print $this->schedule->getId(); ?>' name='message' cols='40' rows='10'></textarea>
			
			<input type='hidden' name='csrf_key' value='<?php print $this->csrfKey(); ?>' />
			<input type='hidden' name='schedule_id' value='<?php print $this->escape($this->schedule->getId()); ?>'/>
		</form>

		<hr/>

		<?php print $this->render('schedules/schedule_email.phtml'); ?>

	</div>

<?php
if (!defined('EMAIL_DIALOG_JS_ADDED')) {
	ob_start();
?>

	$(function() { // on DOM ready 
		
		/*********************************************************
		 * Email controls
		 *********************************************************/
		$(".email_dialog").each(function() {
			var button = $(this).siblings(".email_button");
			var emailDialog = $(this).dialog({
					autoOpen: false, 
					width:  700, 
					modal: true,
					position: 'top'
				});
			
			button.data("emailDialog", emailDialog);
		});
		$(".email_button").click(function(){
			var emailDialog = $(this).data('emailDialog');
			emailDialog.dialog("open");
			
			return false;
		});
		
	});


<?php

	$this->headScript()->appendScript(ob_get_clean());
	define('EMAIL_DIALOG_JS_ADDED', true);
}