<?php 

$this->headScript()->appendScript("
	$(function() { // on DOM ready 
		
		$('form.delete_schedule').submit(function () {
			return confirm('Are you sure you want to delete this schedule?');	
		});
		
	});
");

foreach ($this->schedules as $schedule) {
	print "\n<div class='schedule'>";
	
	print "\n\t<form class='delete_schedule' action='".$this->url(array('action' => 'delete'))."' method='post'>";
	print "\n\t\t<input type='hidden' name='schedule_id' value='".$this->escape($schedule->getId())."'/>";
	print "\n\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."' />";
	print "\n\t\t<input type='submit' value='Delete'/>";
	print "\n\t</form>";
	
	print "\n\t<form action='".$this->url(array('action' => 'update'))."' method='post'>";
	print "\n\t\t<input type='text' name='name' value=\"".$this->escape($schedule->getName())."\"/>";
	print "\n\t\t<input type='hidden' name='schedule_id' value='".$this->escape($schedule->getId())."'/>";
	print "\n\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."' />";
	print "\n\t\t<input type='submit' value='Save Name'/>";
	print "\n\t</form>";
	
	print "\n\t\t<ul>";
	foreach ($schedule->getOfferings() as $offering) {
		print "\n\t\t\t<li class='offering'>";
		
		print "\n\t\t<div class='offering_name'>";
		print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
		print $this->escape($offering->getDisplayName());
		print "</a>";
		print "\n\t\t</div>";
		
		print "\n\t\t<div class='separator'> - </div>";
		
		print "\n\t\t<div class='offering_title'>";
		print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
		print nl2br($this->escape($offering->getTitle()));
		print "</a>";
		print "\n\t\t</div>";
		
		print "\n\t\t\t</li>";
	}
	print "\n\t\t</ul>";
	
	print "\n</div>";
}

?>

<form id='schedule_create' action="<?php print $this->url(array('action' => 'create')); ?>" method="post">
	<input type="submit" value="Create new schedule"/> for 
	<?php print $this->render('schedules/terms.phtml'); ?>
	
	<input type="hidden" name="catalog" value="<?php print $this->escape($this->getStringFromOsidId($this->menuCatalogSelectedId)); ?>" />
	<input type="hidden" name="csrf_key" value="<?php print $this->csrfKey(); ?>" />
</form>