<?php

foreach ($this->schedules as $schedule) {
	print "\n<div class='schedule'>";
	
	// Print the Term the schedule is for if we don't have a term selected.
	if (!$this->selectedTermId) {
		print "\n\t<div class='term_name'>";
		print $schedule->getTermName();
		print "</div>";
	}
	
	// Delete Button
	print "\n\t<form class='delete_schedule' action='".$this->url(array('action' => 'delete'))."' method='post'>";
	print "\n\t\t<input type='hidden' name='schedule_id' value='".$this->escape($schedule->getId())."'/>";
	print "\n\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."' />";
	print "\n\t\t<input type='submit' value='Delete'/>";
	print "\n\t</form>";
	
	// Schedule name
	print "\n\t<form action='".$this->url(array('action' => 'update'))."' method='post'>";
	print "\n\t\t<input type='text' name='name' value=\"".$this->escape($schedule->getName())."\"/>";
	print "\n\t\t<input type='hidden' name='schedule_id' value='".$this->escape($schedule->getId())."'/>";
	print "\n\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."' />";
	print "\n\t\t<input type='submit' value='Save Name'/>";
	print "\n\t</form>";
	
	// Print view.
	print "\n\t<a class='print_button' href='".$this->url(array('action' => 'print', 'schedule_id' => $schedule->getId()))."' title='Click for print view.' target='print_view'>";
	print "\n\t<button>Print</button>";
	print "\n\t\t</a>";
	
	// Email view.
	print "\n\t<a class='email_button' href='#' title='Click for print view.'>";
	print "\n\t<button>EMail</button>";
	print "\n\t\t</a>";
	
	print "\n\t<div class='email_dialog' style='display: none;' title=\"".$this->escape($schedule->getName())."\">";
	
	print "\n\n<p class='notice'><strong>This feature is not yet operational. Please check back in a few days.</strong></p>";
	
	print "\n\t\t<form action='".$this->url(array('action' => 'email'))."' method='post'>";
	print "\n\t\t\t<label for='from-".$schedule->getId()."'>From: </label><input id='from-".$schedule->getId()."' name='from' type='text' value='".$this->getUserDisplayName()."' readonly='readonly' size='42'/>";
	print "\n\t\t\t<br/><label for='to-".$schedule->getId()."'>To: </label><input id='to-".$schedule->getId()."' name='to' type='text' size='42'/>";
	print "\n\t\t\t<br/><label for='subject-".$schedule->getId()."'>Subject:</label><input id='subject-".$schedule->getId()."' name='subject' type='text' value=\"".$this->escape($schedule->getName())."\" size='42'/>";
	print "\n\t\t\t<br/><label for='message-".$schedule->getId()."'> &nbsp; </label><textarea id='message-".$schedule->getId()."' name='message' type='text' value='' cols='40' rows='10'></textarea>";
	print "\n\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."' />";
	print "\n\t\t<input type='hidden' name='schedule_id' value='".$this->escape($schedule->getId())."'/>";
	print "\n\t\t</form>";
	
	print "\n\t\t<hr/>";
	
	$this->schedule = $schedule;
	print $this->render('schedules/schedule_email.phtml');
	
	print "</div>";
	
	// Calendar
	print "\n\t<a class='calendar_button' href='".$this->url(array('action' => 'eventsjson', 'schedule_id' => $schedule->getId()))."' title='Click to zoom'>";
	print "\n\t<img class='calendar_img' src='".$this->url(array('action' => 'png', 'schedule_id' => $schedule->getId()))."' alt='Weekly Schedule Image'/>";
	print "\n\t\t</a>";
	
	print "\n\t<div class='calendar' style='display: none;' title=\"".$this->escape($schedule->getName())."\">";
	print "\n\t\t<input type='hidden' name='start_hour' value='".($schedule->getEarliestHour())."'/>";
	print "\n\t\t<input type='hidden' name='end_hour' value='".($schedule->getLatestHour() + 1)."'/>";
	print "\n\t\t<input type='hidden' name='show_sunday' value='".(($schedule->hasEventsOnSunday())?'yes':'no')."'/>";
	print "\n\t\t<input type='hidden' name='show_saturday' value='".(($schedule->hasEventsOnSaturday())?'yes':'no')."'/>";
	print "</div>";
	
	
	print "\n\t\t<ul class='offerings'>";
	$offerings = $schedule->getOfferings();
	if (!count($offerings)) {
		print "\n\t\t\t<li style='visibility: hidden'> &nbsp; </li>";
	}
	foreach ($offerings as $offering) {
		print "\n\t\t\t<li class='offering'>";
		
		// Remove/Change Dialog.
		print "\n\t\t<div title='Remove or Change Sections' class='remove_dialog'>";
		print "<p>What do you want to do?</p>";
		
		// Change form
		$scheduleTermIdString = $this->getStringFromOsidId($schedule->getTermId());
?>
		<button class='change_sections_button'>Change sections</button>
		<div class="change_section_dialog section_dialog" title="Include which sections?" style='display: none'>
			<form action="<?php print $this->url(array('action' => 'add', 'term' => $scheduleTermIdString)); ?>" class="add_section_form" method="post">
				Choose one option from each group:
				<ul class="section_sets">
					<li> &nbsp; </li>
				</ul>
				
				<input type='hidden' name='csrf_key' value='<?php print $this->csrfKey(); ?>' />
				<input type='hidden' name='schedule_id' value='<?php print $schedule->getId(); ?>' />
				<input type="submit" value="Choose Sections"/>
			</form>
			<input type='hidden' name='course_id' value="<?php print $this->getStringFromOsidId($offering->getCourseId()); ?>" />
			<input type='hidden' name='section_lookup_url' value='<?php print $this->url(array('action' => 'sectionsforcourse', 'term' => $scheduleTermIdString)); ?>' />
		</div>
		
<?php
		
		// Remove Form
		print "\n\t\t<form class='remove_offering_form' action='".$this->url(array('action' => 'remove'))."' method='post'>";
		print "\n\t\t\t<input type='hidden' name='csrf_key' value='".$this->csrfKey()."'/>";
		print "\n\t\t\t<input type='hidden' name='schedule_id' value='".$schedule->getId()."'/>";
		print "\n\t\t\t<input type='hidden' name='offering' value='".$this->getStringFromOsidId($offering->getId())."'/>";
		print "\n\t\t\t<input type='submit' value='Remove all sections of ".$this->escape($offering->getCourse()->getDisplayName())."'/>";
		print "\n\t\t</form>";
		
		// Cancel
		print "\n\t\t<button class='cancel'>Cancel</button>";
		
		print "\n\t\t</div>";
		
		// Remove/Change Button.
		print "\n\t\t<button class='remove_button' href='#' title='Remove or Change Sections'>X</button>";
		
		print "\n\t\t<div class='offering_name'>";
		print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
		print $this->escape($offering->getDisplayName());
		print "</a>";
		print "\n\t\t</div>";
		
		print "\n\t\t<div class='separator'> - </div>";
		
		print "\n\t\t<div class='offering_title'>";
		print "\n\t\t\t<a href='".$this->url(array('controller' => 'offerings', 'action' => 'view', 'offering' => $this->getStringFromOsidId($offering->getId())))."' target='_blank'>";
		print nl2br($this->escape($offering->getTitle()));
		print "</a>";
		print "\n\t\t</div>";
		
		print "\n\t\t<div class='time";
		if ($schedule->hasCollisions($offering->getId()))
			print ' conflicting';
		print "'>".nl2br($this->escape($offering->getScheduleInfo()))."</div>";
		print "\n\t\t<div class='location'>".nl2br($this->escape($offering->getLocationInfo()))."</div>";
		
		print "\n\t\t\t</li>";
	}
	print "\n\t\t</ul>";
	
	print "\n</div>";
}

?>

<form id='schedule_create' action="<?php print $this->url(array('action' => 'create')); ?>" method="post">
	<input type="submit" value="Create new schedule"/> for 
	<?php print $this->render('schedules/terms.phtml'); ?>
	
	<input type="hidden" name="catalog" value="<?php print $this->escape($this->getStringFromOsidId($this->menuCatalogSelectedId)); ?>" />
	<input type="hidden" name="csrf_key" value="<?php print $this->csrfKey(); ?>" />
</form>

<?php ob_start(); ?>

	$(function() { // on DOM ready 
		
		$('form.delete_schedule').submit(function () {
			return confirm('Are you sure you want to delete this schedule?');	
		});
		
		$('a.print_button').click(function() {
			var printView = window.open(this.href, this.target, "menubar=1,resizable=1,height=600,width=800,scrollbars=1");
			printView.focus();
			return false;
		});
		
		/*********************************************************
		 * Remove dialog controls
		 *********************************************************/
		$(".remove_dialog").each(function() {
			var button = $(this).siblings(".remove_button");
			var removeDialog = $(this).dialog({
					autoOpen: false, 
					width:  600, 
					modal: true,
					position: 'top'
				});
			
			button.data("removeDialog", removeDialog);
		});
		
		$(".remove_button").click(function(){
			var removeDialog = $(this).data('removeDialog');
			removeDialog.dialog("open");
		});
		
		$(".remove_dialog .cancel").click(function() {
			$(this).parent().dialog('close');
		});
		
		$(".change_section_dialog").each(function () {
			var button = $(this).siblings(".change_sections_button");
			var addDialog = $(this).dialog({
					autoOpen: false, 
					width:  600, 
					modal: true,
					close: function(event, ui) {
						$(this).find("ul.section_sets").empty();
					}
				});
			
			button.data("addDialog", addDialog);
		});
		
		$(".change_sections_button").click(function () {
			var removeDialog = $(this).parent();
			removeDialog.dialog("close");
			
			var addDialog = $(this).data("addDialog");
			var scheduleId = addDialog.find("input[name=schedule_id]").val();
						
			addDialog.find("ul.section_sets").empty();
			getSectionSets(addDialog, scheduleId);
			addDialog.dialog("open");
		});
		
		
		
		/*********************************************************
		 * Calendar controls
		 *********************************************************/
		<?php
		$this->headLink()->appendStylesheet($this->url(array(), null, true).'javascript/jquery-week-calendar/jquery.weekcalendar.css');
		$this->headStyle()->appendStyle('
			div.wc-toolbar {display: none;}
			.wc-time-slots .wc-today { background-color: #FFF; }
			.wc-header .wc-today { font-weight: normal; }
		');
		$this->headScript()->appendFile($this->url(array(), null, true).'javascript/jquery-week-calendar/libs/date.js');
		$this->headScript()->appendFile($this->url(array(), null, true).'javascript/jquery-week-calendar/jquery.weekcalendar.js');
		$this->headScript()->appendFile($this->url(array(), null, true).'javascript/schedule.js');

		?>
		
		$(".calendar").each(function() {
			var button = $(this).siblings(".calendar_button");
			var calendar = $(this).dialog({
					autoOpen: false, 
					width:  900, 
					modal: true,
					position: 'top'
				});
			
			button.data("calendar", calendar);
		});
		$(".calendar_button").click(function(){
			var jsonUrl = $(this).attr('href');
			var calendar = $(this).data('calendar');
			calendar.dialog("open");
			
			if (!calendar.data('initialized')) {
				renderSchedule(calendar, jsonUrl);
				calendar.data('initialized', true);
			}
			
			return false;
		});
		
		/*********************************************************
		 * Email controls
		 *********************************************************/
		$(".email_dialog").each(function() {
			var button = $(this).siblings(".email_button");
			var emailDialog = $(this).dialog({
					autoOpen: false, 
					width:  700, 
					modal: true,
					position: 'top'
				});
			
			button.data("emailDialog", emailDialog);
		});
		$(".email_button").click(function(){
			var emailDialog = $(this).data('emailDialog');
			emailDialog.dialog("open");
			
			return false;
		});
		
	});


<?php

$this->headScript()->appendScript(ob_get_clean());