				<select name="term">
					<option value='<?php print $this->url(array('term' => 'ANY')); ?>'>All Terms</option>
<?php
foreach($this->terms as $termInfo) {
	print "\n\t\t\t\t\t<option value='";
	print $termInfo['url'];
	print "'";
	if (isset($this->selectedTermId) && $termInfo['id']->isEqual($this->selectedTermId))
		print " selected='selected'";
	print ">".$termInfo['name']."</option>";
}
?>
				</select>
